# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-23 09:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import localflavor.generic.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reference', '0004_auto_20160531_1035'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.IntegerField()),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation_code', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('birth_place', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, choices=[('FEMALE', 'female'), ('MALE', 'male')], max_length=20, null=True)),
                ('civil_status', models.CharField(blank=True, choices=[('MARRIED', 'married'), ('SINGLE', 'single'), ('WIDOWED', 'widowed'), ('DIVORCED', 'divorced'), ('SEPARATED', 'separated'), ('COHABITANT', 'cohabitant'), ('UNKNOWN', 'unknown')], default='UNKNOWN', max_length=20, null=True)),
                ('number_children', models.IntegerField(blank=True, null=True)),
                ('spouse_name', models.CharField(blank=True, max_length=50, null=True)),
                ('national_id', models.CharField(blank=True, max_length=25, null=True)),
                ('id_card_number', models.CharField(blank=True, max_length=25, null=True)),
                ('passport_number', models.CharField(blank=True, max_length=25, null=True)),
                ('phone_mobile', models.CharField(blank=True, max_length=30, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('additional_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('registration_id', models.CharField(blank=True, max_length=20, null=True)),
                ('last_academic_year', models.IntegerField(blank=True, null=True)),
                ('language', models.CharField(choices=[('fr-be', 'French'), ('en', 'English')], default='fr-be', max_length=30, null=True)),
                ('birth_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reference.Country')),
                ('nationality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_nationality', to='reference.Country')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('application_type', models.CharField(choices=[('ADMISSION', 'admission'), ('INSCRIPTION', 'inscription')], max_length=20)),
                ('doctorate', models.BooleanField(default=False)),
                ('national_degree', models.NullBooleanField(default=None)),
                ('valuation_possible', models.NullBooleanField(default=None)),
                ('started_similar_studies', models.NullBooleanField(default=None)),
                ('credits_to_value', models.NullBooleanField(default=None)),
                ('applied_to_sameprogram', models.NullBooleanField(default=None)),
                ('resident', models.NullBooleanField(default=None)),
                ('raffle_number', models.CharField(blank=True, max_length=50, null=True)),
                ('study_grant', models.BooleanField(default=False)),
                ('study_grant_number', models.CharField(blank=True, max_length=50, null=True)),
                ('deduction_children', models.BooleanField(default=False)),
                ('scholarship', models.BooleanField(default=False)),
                ('scholarship_organization', models.TextField(blank=True, null=True)),
                ('sport_membership', models.BooleanField(default=False)),
                ('culture_membership', models.BooleanField(default=False)),
                ('solidarity_membership', models.BooleanField(default=False)),
                ('bank_account_iban', localflavor.generic.models.IBANField(False, ('AT', 'BE', 'BG', 'CH', 'CY', 'CZ', 'DE', 'DK', 'EE', 'ES', 'FI', 'FR', 'GB', 'GI', 'GR', 'HR', 'HU', 'IE', 'IS', 'IT', 'LI', 'LT', 'LU', 'LV', 'MC', 'MT', 'NL', 'NO', 'PL', 'PT', 'RO', 'SE', 'SI', 'SK', 'SM'), blank=True, null=True)),
                ('bank_account_bic', localflavor.generic.models.BICField(blank=True, null=True)),
                ('bank_account_name', models.CharField(blank=True, max_length=255, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.Applicant')),
            ],
        ),
        migrations.CreateModel(
            name='AssimilationCriteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria', models.CharField(max_length=255, unique=True)),
                ('order', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_type', models.CharField(choices=[('LOCAL_UNIVERSITY', 'national_university'), ('FOREIGN_UNIVERSITY', 'foreign_university'), ('LOCAL_HIGH_EDUCATION', 'high_national_non_university'), ('FOREIGN_HIGH_EDUCATION', 'high_foreign_non_university'), ('ANOTHER_ACTIVITY', 'other')], max_length=25)),
                ('national_education', models.CharField(blank=True, choices=[('FRENCH', 'Communauté française de Belgique'), ('GERMAN', 'Communauté germanophone'), ('DUTCH', 'Communauté flamande')], max_length=20, null=True)),
                ('grade_type_no_university', models.CharField(blank=True, choices=[('HIGHER_NON_UNIVERSITY', 'higher_non_university'), ('BACHELOR', 'bachelor'), ('MASTER', 'master'), ('OTHER', 'other')], max_length=25, null=True)),
                ('result', models.CharField(blank=True, choices=[('SUCCEED', 'succeeded'), ('FAILED', 'failed'), ('NO_RESULT', 'no_result')], max_length=20, null=True)),
                ('credits_enrolled', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('credits_obtained', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('diploma', models.BooleanField(default=False)),
                ('diploma_title', models.CharField(blank=True, max_length=255, null=True)),
                ('activity_type', models.CharField(blank=True, choices=[('JOB', 'job'), ('INTERNSHIP', 'internship'), ('VOLUNTEERING', 'volunteering'), ('UNEMPLOYMENT', 'unemployment'), ('ILLNESS', 'illness'), ('OTHER', 'other')], max_length=255, null=True)),
                ('activity', models.CharField(blank=True, max_length=255, null=True)),
                ('activity_place', models.CharField(blank=True, max_length=255, null=True)),
                ('study_system', models.CharField(blank=True, choices=[('SOCIAL_ADVANCEMENT', 'social_advancement'), ('FULL_EXERCISE', 'full_exercise')], max_length=25, null=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.AcademicYear')),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(max_length=255)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admission.Domain')),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GradeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(max_length=255)),
                ('grade', models.CharField(choices=[('BACHELOR', 'bachelor'), ('MASTER', 'master'), ('DOCTORATE', 'ph_d'), ('TRAINING_CERTIFICATE', 'teacher_training_certificate'), ('CERTIFICATE', 'certificate')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('subject', models.CharField(max_length=255)),
                ('template', models.TextField()),
                ('format', models.CharField(choices=[('PLAIN', 'plain'), ('HTML', 'html'), ('PLAIN_HTML', 'plain_and_html')], max_length=15)),
                ('language', models.CharField(choices=[('FR', 'french'), ('EN', 'english')], default='FR', max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OfferYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=100, null=True)),
                ('acronym', models.CharField(max_length=15)),
                ('title', models.CharField(max_length=255)),
                ('title_international', models.CharField(blank=True, max_length=255, null=True)),
                ('subject_to_quota', models.BooleanField(default=False)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.AcademicYear')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.Domain')),
                ('grade_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admission.GradeType')),
            ],
        ),
        migrations.CreateModel(
            name='OfferYearCalendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('offer_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.OfferYear')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('value', models.TextField()),
                ('order', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PersonAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('LEGAL', 'Legal'), ('CONTACT', 'Contact')], max_length=20)),
                ('street', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=6)),
                ('complement', models.CharField(blank=True, max_length=255, null=True)),
                ('postal_code', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=255)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference.Country')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.Applicant')),
            ],
        ),
        migrations.CreateModel(
            name='PersonAssimilationCriteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.AssimilationCriteria')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.Applicant')),
            ],
        ),
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('INSTITUTION', 'Institution'), ('LOGO', 'Logo'), ('PROFESSIONAL_EXAM_LINK', 'Professional exam link'), ('LOCAL_LANGUAGE_EXAM_LINK', 'Local language exam link')], max_length=255)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('LABEL', 'label'), ('SHORT_INPUT_TEXT', 'short_input_text'), ('LONG_INPUT_TEXT', 'long_input_text'), ('RADIO_BUTTON', 'radio_button'), ('CHECKBOX', 'checkbox'), ('DROPDOWN_LIST', 'dropdown_list'), ('UPLOAD_BUTTON', 'Upuload_button'), ('DOWNLOAD_LINK', 'download_link'), ('HTTP_LINK', 'HTTP_link')], max_length=20)),
                ('order', models.IntegerField()),
                ('required', models.BooleanField(default=False)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.Form')),
            ],
        ),
        migrations.CreateModel(
            name='SecondaryEducation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diploma', models.BooleanField(default=False)),
                ('national', models.NullBooleanField(default=True)),
                ('national_community', models.CharField(blank=True, choices=[('FRENCH', 'Communauté française de Belgique'), ('GERMAN', 'Communauté germanophone'), ('DUTCH', 'Communauté flamande')], max_length=20, null=True)),
                ('dipl_acc_high_educ', models.NullBooleanField(default=False)),
                ('path_repetition', models.NullBooleanField(default=False)),
                ('path_reorientation', models.NullBooleanField(default=False)),
                ('result', models.CharField(blank=True, choices=[('LOW', 'Moins de 65%'), ('MIDDLE', 'entre 65% et 75%'), ('HIGH', 'plus de 75%')], max_length=20, null=True)),
                ('international_diploma', models.CharField(blank=True, choices=[('NATIONAL', "Baccalauréat national (ou diplôme d'état, ...)"), ('EUROPEAN', 'Baccalauréat européen (Schola Europea)'), ('INTERNATIONAL', 'Baccalauréat international(IBO)')], max_length=20, null=True)),
                ('international_equivalence', models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No'), ('DEMANDED', 'Demanded')], max_length=20, null=True)),
                ('admission_exam', models.NullBooleanField(default=False)),
                ('admission_exam_date', models.DateField(blank=True, null=True)),
                ('admission_exam_institution', models.CharField(blank=True, max_length=100, null=True)),
                ('admission_exam_result', models.CharField(blank=True, choices=[('LOW', 'Moins de 65%'), ('MIDDLE', 'entre 65% et 75%'), ('HIGH', 'plus de 75%')], max_length=20, null=True)),
                ('professional_exam', models.NullBooleanField(default=False)),
                ('professional_exam_date', models.DateField(blank=True, null=True)),
                ('professional_exam_institution', models.CharField(blank=True, max_length=100, null=True)),
                ('professional_exam_result', models.CharField(blank=True, choices=[('LOW', 'Moins de 65%'), ('MIDDLE', 'entre 65% et 75%'), ('HIGH', 'plus de 75%')], max_length=20, null=True)),
                ('local_language_exam', models.NullBooleanField(default=False)),
                ('local_language_exam_date', models.DateField(blank=True, null=True)),
                ('local_language_exam_institution', models.CharField(blank=True, max_length=100, null=True)),
                ('local_language_exam_result', models.CharField(blank=True, choices=[('SUCCEED', 'succeeded'), ('FAILED', 'failed'), ('ENROLLMENT_IN_PROGRESS', 'demanded_result')], max_length=25, null=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admission.AcademicYear')),
                ('admission_exam_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reference.AdmissionExamType')),
                ('education_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reference.EducationType')),
                ('international_diploma_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reference.Country')),
                ('international_diploma_language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reference.Language')),
                ('national_institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reference.EducationInstitution')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admission.Applicant')),
            ],
        ),
        migrations.AddField(
            model_name='option',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.Question'),
        ),
        migrations.AddField(
            model_name='form',
            name='offer_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.OfferYear'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Curriculum_domain', to='admission.Domain'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='grade_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admission.GradeType'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reference.Language'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='national_institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reference.EducationInstitution'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.Applicant'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='sub_domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Curriculum_sub_domain', to='admission.Domain'),
        ),
        migrations.AddField(
            model_name='application',
            name='offer_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.OfferYear'),
        ),
        migrations.AddField(
            model_name='answer',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.Application'),
        ),
        migrations.AddField(
            model_name='answer',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.Option'),
        ),
    ]
