# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-18 11:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.IntegerField()),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('application_type', models.CharField(choices=[('ADMISSION', 'Admission'), ('INSCRIPTION', 'Inscription')], max_length=20)),
                ('doctorate', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GradeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(max_length=255)),
                ('grade', models.CharField(choices=[('BACHELOR', 'Bachelor'), ('MASTER', 'Master'), ('DOCTORATE', 'Ph.D')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('subject', models.CharField(max_length=255)),
                ('template', models.TextField()),
                ('format', models.CharField(choices=[('PLAIN', 'Plain'), ('HTML', 'HTML'), ('PLAIN_HTML', 'Plain and HTML')], max_length=15)),
                ('language', models.CharField(choices=[('FR', 'Français'), ('EN', 'English')], default='FR', max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OfferYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=100, null=True)),
                ('acronym', models.CharField(max_length=15)),
                ('title', models.CharField(max_length=255)),
                ('title_international', models.CharField(blank=True, max_length=255, null=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.AcademicYear')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.Domain')),
                ('grade_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admission.GradeType')),
            ],
        ),
        migrations.CreateModel(
            name='OfferYearCalendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('offer_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.OfferYear')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='offer_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.OfferYear'),
        ),
        migrations.AddField(
            model_name='application',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.Person'),
        ),
    ]
