# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-15 11:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0001_initial'),
        ('admission', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantAssimilationCriteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.Applicant')),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference.AssimilationCriteria')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationAssimilationCriteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.Application')),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference.AssimilationCriteria')),
            ],
        ),
        migrations.RemoveField(
            model_name='personassimilationcriteria',
            name='criteria',
        ),
        migrations.RemoveField(
            model_name='personassimilationcriteria',
            name='person',
        ),
        migrations.DeleteModel(
            name='PersonAssimilationCriteria',
        ),
    ]
