# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-15 12:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0002_domain'),
        ('admission', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantAssimilationCriteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.Applicant')),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference.AssimilationCriteria')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationAssimilationCriteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.Application')),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference.AssimilationCriteria')),
            ],
        ),
        migrations.RemoveField(
            model_name='domain',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='personassimilationcriteria',
            name='criteria',
        ),
        migrations.RemoveField(
            model_name='personassimilationcriteria',
            name='person',
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Curriculum_domain', to='reference.Domain'),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='sub_domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Curriculum_sub_domain', to='reference.Domain'),
        ),
        migrations.AlterField(
            model_name='offeryear',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference.Domain'),
        ),
        migrations.DeleteModel(
            name='Domain',
        ),
        migrations.DeleteModel(
            name='PersonAssimilationCriteria',
        ),
    ]
