# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 08:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0002_auto_20160318_1114'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.Application')),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('offer_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.OfferYear')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('value', models.TextField()),
                ('order', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('LABEL', 'Label'), ('SHORT_INPUT_TEXT', 'Short input text'), ('LONG_INPUT_TEXT', 'Long input text'), ('RADIO_BUTTTON', 'Radio button'), ('CHECKBOX', 'Checkbox'), ('CHECKBOX', 'Checkbox'), ('DROPDOWN_LIST', 'Dropdown list'), ('UPLOAD_BUTTON', 'Upload button'), ('DOWNLOAD_LINK', 'Download link'), ('HTTP_LINK', 'HTTP link')], max_length=20)),
                ('order', models.IntegerField()),
                ('required', models.BooleanField(default=False)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.Form')),
            ],
        ),
        migrations.AddField(
            model_name='option',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.Question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.Option'),
        ),
    ]
