# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-20 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0002_auto_20161010_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='application_type',
            field=models.CharField(choices=[('ADMISSION', 'ADMISSION'), ('INSCRIPTION', 'INSCRIPTION')], max_length=20),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='academic_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='secondaryeducation',
            name='academic_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
