# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-08 10:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0002_auto_20160715_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationassimilationcriteria',
            name='application',
        ),
        migrations.RemoveField(
            model_name='applicationassimilationcriteria',
            name='criteria',
        ),
        migrations.DeleteModel(
            name='ApplicationAssimilationCriteria',
        ),
    ]
