# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 09:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0002_auto_20160318_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admission.Domain'),
        ),
    ]
