# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-29 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0002_auto_20160422_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssimilationCriteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
