# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-25 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0003_auto_20161020_0657'),
    ]

    operations = [
        migrations.AddField(
            model_name='profession',
            name='adhoc',
            field=models.BooleanField(default=False),
        ),
    ]
