# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-24 10:15
from __future__ import unicode_literals
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist

from django.db import migrations, models
import django.db.models.deletion
from admission.models.applicant_document_file import ApplicantDocumentFile
from osis_common.models.document_file import DocumentFile
from admission.models import applicant as mdl_applicant


def populate_applicant_document_file(apps, schema_editor):
    document_files = DocumentFile.objects.all()
    for document_file in document_files:
        if document_file.username != 'system':
            user = User.objects.get(username=document_file.username)
            try:
                applicant = mdl_applicant.find_by_user(user)
                applicant_document_file = ApplicantDocumentFile(applicant=applicant, document_file=document_file)
                applicant_document_file.save()
            except ObjectDoesNotExist:
                pass


class Migration(migrations.Migration):
    dependencies = [
        ('osis_common', '0010_documentfile_username'),
        ('admission', '0003_auto_20161020_0657'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantDocumentFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.Applicant')),
                ('document_file',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osis_common.DocumentFile')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='applicantdocumentfile',
            unique_together=set([('applicant', 'document_file')]),
        ),
        migrations.RunPython(populate_applicant_document_file)
    ]
