# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-10 13:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0003_update_application_assimilitaion_criteria'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessageTemplate',
        ),
    ]
