# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-17 12:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osis_common', '0002_documentfile'),
        ('reference', '0002_domain'),
        ('admission', '0004_delete_messagetemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationDocumentFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.Application')),
                ('document_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osis_common.DocumentFile')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentTypeAssimilation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=50)),
                ('assimilation_criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference.AssimilationCriteria')),
            ],
        ),
    ]
