# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-25 14:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('admission', '0005_auto_20161025_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferAdmissionExamType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_exam_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.AdmissionExamType')),
                ('offer_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.OfferYear')),
            ],
        ),
    ]
