# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-05 13:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_offer'),
        ('admission', '0005_applicationdocumentfile_documenttypeassimilation'),
    ]

    operations = [
        migrations.AddField(
            model_name='offeryear',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Offer'),
        ),
    ]
