# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-07 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0006_personaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('INSTITUTION', 'Institution'), ('LOGO', 'Logo')], max_length=255)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('LABEL', 'Label'), ('SHORT_INPUT_TEXT', 'Short input text'), ('LONG_INPUT_TEXT', 'Long input text'), ('RADIO_BUTTON', 'Radio button'), ('CHECKBOX', 'Checkbox'), ('DROPDOWN_LIST', 'Dropdown list'), ('UPLOAD_BUTTON', 'Upload button'), ('DOWNLOAD_LINK', 'Download link'), ('HTTP_LINK', 'HTTP link')], max_length=20),
        ),
    ]
