# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-06 12:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20160906_1253'),
        ('admission', '0006_offeryear_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offeryear',
            name='domain',
        ),
        migrations.AddField(
            model_name='offeryear',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Campus'),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='national_education',
            field=models.CharField(blank=True, choices=[('FRENCH', 'FRENCH'), ('GERMAN', 'GERMAN'), ('DUTCH', 'DUTCH')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='secondaryeducation',
            name='national_community',
            field=models.CharField(blank=True, choices=[('FRENCH', 'FRENCH'), ('GERMAN', 'GERMAN'), ('DUTCH', 'DUTCH')], max_length=20, null=True),
        ),
    ]
