# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-08 20:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dissertation', '0002_auto_20160908_2039'),
        ('admission', '0006_offeryear_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offeryear',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='offeryear',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='offeryear',
            name='grade_type',
        ),
        migrations.RemoveField(
            model_name='offeryear',
            name='offer',
        ),
        migrations.AlterField(
            model_name='application',
            name='offer_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.OfferYear'),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.AcademicYear'),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='national_education',
            field=models.CharField(blank=True, choices=[('FRENCH', 'FRENCH'), ('GERMAN', 'GERMAN'), ('DUTCH', 'DUTCH')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='offer_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.OfferYear'),
        ),
        migrations.AlterField(
            model_name='secondaryeducation',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.AcademicYear'),
        ),
        migrations.AlterField(
            model_name='secondaryeducation',
            name='national_community',
            field=models.CharField(blank=True, choices=[('FRENCH', 'FRENCH'), ('GERMAN', 'GERMAN'), ('DUTCH', 'DUTCH')], max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='AcademicYear',
        ),
    ]
