# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-08 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0007_create_and_populate_applicant_document_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociologicalsurvey',
            name='father_education',
            field=models.CharField(blank=True, choices=[('UNKNOWN', 'UNKNOWN'), ('PRIMARY', 'PRIMARY'), ('SECONDARY_INFERIOR', 'SECONDARY_INFERIOR'), ('SECONDARY_SUPERIOR', 'SECONDARY_SUPERIOR'), ('SUPERIOR_NON_UNIVERSITY', 'SUPERIOR_NON_UNIVERSITY'), ('UNIVERSITY', 'UNIVERSITY')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='sociologicalsurvey',
            name='mother_education',
            field=models.CharField(blank=True, choices=[('UNKNOWN', 'UNKNOWN'), ('PRIMARY', 'PRIMARY'), ('SECONDARY_INFERIOR', 'SECONDARY_INFERIOR'), ('SECONDARY_SUPERIOR', 'SECONDARY_SUPERIOR'), ('SUPERIOR_NON_UNIVERSITY', 'SUPERIOR_NON_UNIVERSITY'), ('UNIVERSITY', 'UNIVERSITY')], max_length=40, null=True),
        ),
    ]
