# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-07 12:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0007_auto_20160407_1250'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE auth_user ALTER COLUMN username TYPE varchar(254);"
        ),
    ]
