# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-09 14:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0007_profession_sociologicalsurvey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secondaryeducationexam',
            name='admission_exam_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admission.AdmissionExamType'),
        ),
    ]
