# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-08 20:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dissertation', '0002_auto_20160908_2039'),
        ('base', '0010_auto_20160908_2039'),
        ('admission', '0007_auto_20160908_2039'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OfferYear',
        ),
    ]
