# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-09 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0008_auto_20161108_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='national_degree',
        ),
        migrations.AddField(
            model_name='application',
            name='coverage_access_degree',
            field=models.CharField(blank=True, choices=[('NATIONAL', 'NATIONAL'), ('NON_NATIONAL', 'NON_NATIONAL'), ('EUROPEAN_UNION', 'EUROPEAN_UNION'), ('NON_EUROPEAN_UNION', 'NON_EUROPEAN_UNION')], max_length=30, null=True),
        ),
    ]
