# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-10 07:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0008_auto_20160510_0650'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssimilationCriteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria', models.CharField(max_length=255, unique=True)),
                ('order', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonAssimilationCriteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.AssimilationCriteria')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.Person')),
            ],
        ),
    ]
