# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-19 07:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0002_admissionexamtype_educationinstitution_educationtype_language'),
        ('admission', '0009_assimilationcriteria_personassimilationcriteria'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecondaryEducation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secondary_education_diploma', models.BooleanField(default=False)),
                ('national', models.NullBooleanField(default=True)),
                ('national_community', models.CharField(blank=True, choices=[('FRENCH', 'Communauté française de Belgique'), ('GERMAN', 'Communauté germanophone'), ('DUTCH', 'Communauté flamande')], max_length=20, null=True)),
                ('daes', models.NullBooleanField(default=False)),
                ('path_repetition', models.NullBooleanField(default=False)),
                ('path_reorientation', models.NullBooleanField(default=False)),
                ('result', models.CharField(blank=True, choices=[('LOW', 'Moins de 65%'), ('MIDDLE', 'entre 65% et 75%'), ('HIGH', 'plus de 75%')], max_length=20, null=True)),
                ('international_diploma', models.CharField(blank=True, choices=[('NATIONAL', "Baccalauréat national (ou diplôme d'état, ...)"), ('EUROPEAN', 'Baccalauréat européen (Schola Europea)'), ('INTERNATIONAL', 'Baccalauréat international(IBO)')], max_length=20, null=True)),
                ('international_equivalence', models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No'), ('DEMANDED', 'Demanded')], max_length=20, null=True)),
                ('admission_exam', models.NullBooleanField(default=False)),
                ('admission_exam_date', models.DateField(blank=True, null=True)),
                ('admission_exam_institution', models.CharField(blank=True, max_length=100, null=True)),
                ('admission_exam_result', models.CharField(blank=True, choices=[('LOW', 'Moins de 65%'), ('MIDDLE', 'entre 65% et 75%'), ('HIGH', 'plus de 75%')], max_length=20, null=True)),
                ('professional_exam', models.NullBooleanField(default=False)),
                ('professional_exam_date', models.DateField(blank=True, null=True)),
                ('professional_exam_institution', models.CharField(blank=True, max_length=100, null=True)),
                ('professional_exam_result', models.CharField(blank=True, choices=[('LOW', 'Moins de 65%'), ('MIDDLE', 'entre 65% et 75%'), ('HIGH', 'plus de 75%')], max_length=20, null=True)),
                ('local_language_exam', models.NullBooleanField(default=False)),
                ('local_language_exam_date', models.DateField(blank=True, null=True)),
                ('local_language_exam_institution', models.CharField(blank=True, max_length=100, null=True)),
                ('local_language_exam_result', models.CharField(blank=True, choices=[('LOW', 'Moins de 65%'), ('MIDDLE', 'entre 65% et 75%'), ('HIGH', 'plus de 75%')], max_length=25, null=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admission.AcademicYear')),
                ('admission_exam_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reference.AdmissionExamType')),
                ('education_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reference.EducationType')),
                ('international_diploma_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reference.Country')),
                ('international_diploma_language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reference.Language')),
                ('national_institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reference.EducationInstitution')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='language',
            field=models.CharField(choices=[('fr-be', 'French'), ('en', 'English')], default='fr-be', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='application_type',
            field=models.CharField(choices=[('ADMISSION', 'admission'), ('INSCRIPTION', 'inscription')], max_length=20),
        ),
        migrations.AlterField(
            model_name='gradetype',
            name='grade',
            field=models.CharField(choices=[('BACHELOR', 'bachelor'), ('MASTER', 'master'), ('DOCTORATE', 'ph_d'), ('TRAINING_CERTIFICATE', 'teacher_training_certificate'), ('CERTIFICATE', 'certificate')], max_length=20),
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='format',
            field=models.CharField(choices=[('PLAIN', 'plain'), ('HTML', 'html'), ('PLAIN_HTML', 'plain_and_html')], max_length=15),
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='language',
            field=models.CharField(choices=[('FR', 'french'), ('EN', 'english')], default='FR', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='civil_status',
            field=models.CharField(blank=True, choices=[('MARRIED', 'married'), ('SINGLE', 'single'), ('WIDOWED', 'widowed'), ('DIVORCED', 'divorced'), ('SEPARATED', 'separated'), ('COHABITANT', 'cohabitant'), ('UNKNOWN', 'unknown')], default='UNKNOWN', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(blank=True, choices=[('FEMALE', 'female'), ('MALE', 'male')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='properties',
            name='key',
            field=models.CharField(choices=[('INSTITUTION', 'Institution'), ('LOGO', 'Logo'), ('PROFESSIONAL_EXAM_LINK', 'Professional exam link'), ('LOCAL_LANGUAGE_EXAM_LINK', 'Local language exam link')], max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('LABEL', 'label'), ('SHORT_INPUT_TEXT', 'short_input_text'), ('LONG_INPUT_TEXT', 'long_input_text'), ('RADIO_BUTTON', 'radio_button'), ('CHECKBOX', 'checkbox'), ('DROPDOWN_LIST', 'dropdown_list'), ('UPLOAD_BUTTON', 'Upuload_button'), ('DOWNLOAD_LINK', 'download_link'), ('HTTP_LINK', 'HTTP_link')], max_length=20),
        ),
        migrations.AddField(
            model_name='secondaryeducation',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admission.Person'),
        ),
    ]
