# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-09 15:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20160909_1522'),
        ('dissertation', '0004_auto_20160909_1522'),
        ('admission', '0009_auto_20160909_1522'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OfferYear',
        ),
    ]
