# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-17 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0009_auto_20160914_0729'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantassimilationcriteria',
            name='selected',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='applicationassimilationcriteria',
            name='selected',
            field=models.NullBooleanField(),
        ),
    ]
