# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-19 08:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0003_educationinstitution_country'),
        ('admission', '0010_auto_20160519_0751'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_type', models.CharField(choices=[('LOCAL_UNIVERSITY', 'national_university'), ('FOREIGN_UNIVERSITY', 'foreign_university'), ('LOCAL_HIGH_EDUCATION', 'high_national_non_university'), ('FOREIGN_HIGH_EDUCATION', 'high_foreign_non_university'), ('ANOTHER_ACTIVITY', 'other')], max_length=25)),
                ('national_education', models.CharField(blank=True, choices=[('FRENCH', 'Communauté française de Belgique'), ('GERMAN', 'Communauté germanophone'), ('DUTCH', 'Communauté flamande')], max_length=20, null=True)),
                ('result', models.CharField(blank=True, choices=[('SUCCEED', 'succeeded'), ('FAILED', 'failed'), ('NO_RESULT', 'no_result')], max_length=20, null=True)),
                ('credits_enrolled', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('credits_obtained', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('diploma', models.BooleanField(default=False)),
                ('diploma_title', models.CharField(blank=True, max_length=255, null=True)),
                ('activity_type', models.CharField(blank=True, choices=[('JOB', 'Job'), ('INTERNSHIP', 'internship'), ('VOLUNTEERING', 'volunteering'), ('UNEMPLOYMENT', 'unemployment'), ('ILLNESS', 'illness'), ('OTHER', 'other')], max_length=255, null=True)),
                ('activity', models.CharField(blank=True, max_length=255, null=True)),
                ('activity_place', models.CharField(blank=True, max_length=255, null=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.AcademicYear')),
                ('domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Curriculum_domain', to='admission.Domain')),
                ('grade_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admission.GradeType')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reference.Language')),
                ('national_institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reference.EducationInstitution')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.Person')),
                ('sub_domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Curriculum_sub_domain', to='admission.Domain')),
            ],
        ),
        migrations.AlterField(
            model_name='secondaryeducation',
            name='local_language_exam_result',
            field=models.CharField(blank=True, choices=[('SUCCEED', 'succeeded'), ('FAILED', 'failed'), ('ENROLLMENT_IN_PROGRESS', 'demanded_result')], max_length=25, null=True),
        ),
    ]
