# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-31 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0011_auto_20160519_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='grade_type_no_university',
            field=models.CharField(blank=True, choices=[('HIGHER_NON_UNIVERSITY', 'higher_non_university'), ('BACHELOR', 'bachelor'), ('MASTER', 'master'), ('OTHER', 'other')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='study_system',
            field=models.CharField(blank=True, choices=[('SOCIAL_ADVANCEMENT', 'social_advancement'), ('FULL_EXERCISE', 'full_exercise')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='activity_type',
            field=models.CharField(blank=True, choices=[('JOB', 'job'), ('INTERNSHIP', 'internship'), ('VOLUNTEERING', 'volunteering'), ('UNEMPLOYMENT', 'unemployment'), ('ILLNESS', 'illness'), ('OTHER', 'other')], max_length=255, null=True),
        ),
    ]
