# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-19 09:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0003_auto_20160919_0938'),
        ('dissertation', '0005_auto_20160919_0938'),
        ('admission', '0011_auto_20160919_0938'),
        ('base', '0011_auto_20160919_0938'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OfferYear',
        ),
        migrations.AddField(
            model_name='offeryeardomain',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reference.Domain'),
        ),
        migrations.AddField(
            model_name='offeryeardomain',
            name='offer_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.OfferYear'),
        ),
    ]
