# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-18 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0011_auto_20161118_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secondaryeducation',
            name='result',
            field=models.CharField(blank=True, choices=[('LOW', 'low_result'), ('MIDDLE', 'middle_result'), ('HIGH', 'high_result'), ('NO_RESULT', 'pas encore de résultat')], max_length=20, null=True),
        ),
    ]
