# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-25 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0011_auto_20160519_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='applied_to_sameprogram',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='belgian_degree',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='credits_to_value',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='lottery_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='resident',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='started_samestudies',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='vae',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offeryear',
            name='subject_to_quota',
            field=models.BooleanField(default=False),
        ),
    ]
