# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-10 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0012_auto_20161118_1126'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SociologicalSurvey',
        ),
    ]
