# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-26 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0012_auto_20160525_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='applied_to_sameprogram',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='application',
            name='belgian_degree',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='application',
            name='credits_to_value',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='application',
            name='resident',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='application',
            name='started_samestudies',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='application',
            name='vae',
            field=models.NullBooleanField(default=None),
        ),
    ]
