# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-07 07:19
from __future__ import unicode_literals

from django.db import migrations
import localflavor.generic.models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0014_auto_20160606_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='bank_account_bic',
            field=localflavor.generic.models.BICField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='bank_account_iban',
            field=localflavor.generic.models.IBANField(False, ('AT', 'BE', 'BG', 'CH', 'CY', 'CZ', 'DE', 'DK', 'EE', 'ES', 'FI', 'FR', 'GB', 'GI', 'GR', 'HR', 'HU', 'IE', 'IS', 'IT', 'LI', 'LT', 'LU', 'LV', 'MC', 'MT', 'NL', 'NO', 'PL', 'PT', 'RO', 'SE', 'SI', 'SK', 'SM'), blank=True, null=True),
        ),
    ]
