# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-21 09:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0017_auto_20161108_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociologicalsurvey',
            name='applicant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admission.Applicant'),
        ),
        migrations.AlterField(
            model_name='sociologicalsurvey',
            name='father_education',
            field=models.CharField(blank=True, choices=[('UNKNOWN', 'UNKNOWN'), ('PRIMARY', 'PRIMARY'), ('SECONDARY_INFERIOR', 'SECONDARY_INFERIOR'), ('SECONDARY_SUPERIOR', 'SECONDARY_SUPERIOR'), ('SUPERIOR_NON_UNIVERSITY', 'SUPERIOR_NON_UNIVERSITY'), ('UNIVERSITY', 'UNIVERSITY')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='sociologicalsurvey',
            name='mother_education',
            field=models.CharField(blank=True, choices=[('UNKNOWN', 'UNKNOWN'), ('PRIMARY', 'PRIMARY'), ('SECONDARY_INFERIOR', 'SECONDARY_INFERIOR'), ('SECONDARY_SUPERIOR', 'SECONDARY_SUPERIOR'), ('SUPERIOR_NON_UNIVERSITY', 'SUPERIOR_NON_UNIVERSITY'), ('UNIVERSITY', 'UNIVERSITY')], max_length=40, null=True),
        ),
    ]
