# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-07 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0018_auto_20170221_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('LABEL', 'LABEL'), ('SHORT_INPUT_TEXT', 'SHORT_INPUT_TEXT'), ('LONG_INPUT_TEXT', 'LONG_INPUT_TEXT'), ('RADIO_BUTTON', 'RADIO_BUTTON'), ('CHECKBOX', 'CHECKBOX'), ('DROPDOWN_LIST', 'DROPDOWN_LIST'), ('UPLOAD_BUTTON', 'UPLOAD_BUTTON'), ('DOWNLOAD_LINK', 'DOWNLOAD_LINK'), ('HTTP_LINK', 'HTTP_LINK')], max_length=20),
        ),
    ]
