# Generated by Django 2.2.24 on 2021-11-16 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScoreEncoding',
        ),
    ]
