# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-02 07:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_enrollment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examenrollment',
            old_name='program_id',
            new_name='offer_year_acronym',
        ),
    ]
