# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-06 11:03
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_enrollment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamEnrollmentForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_id', models.CharField(max_length=10, unique=True)),
                ('offer_year_id', models.BigIntegerField()),
                ('updated_date', models.DateTimeField()),
                ('form', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.RenameModel(
            old_name='ExamEnrollment',
            new_name='ExamEnrollmentSubmitted',
        ),
    ]
