# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-15 13:23
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_enrollment', '0002_auto_20170306_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examenrollmentform',
            name='offer_enrollment',
        ),
        migrations.AlterField(
            model_name='examenrollmentsubmitted',
            name='offer_enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.OfferEnrollment'),
        ),
        migrations.DeleteModel(
            name='ExamEnrollmentForm',
        ),
    ]
