# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-06 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_enrollment', '0002_auto_20170306_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examenrollmentform',
            name='offer_year_id',
            field=models.BigIntegerField(unique=True),
        ),
    ]
