# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-15 14:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam_enrollment', '0002_auto_20170306_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examenrollmentform',
            name='offer_enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.OfferEnrollment'),
        ),
        migrations.AlterField(
            model_name='examenrollmentsubmitted',
            name='offer_enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.OfferEnrollment'),
        ),
    ]
