# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-03 08:51
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_remove_person_national_id'),
        ('exam_enrollment', '0003_auto_20170315_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamEnrollmentRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', django.contrib.postgres.fields.jsonb.JSONField()),
                ('offer_enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.OfferEnrollment')),
            ],
        ),
    ]
