# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-23 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_enrollment', '0004_examenrollmentrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='examenrollmentrequest',
            name='offer_year_acronym',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
