# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-06 05:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_enrollment', '0005_examenrollmentrequest_offer_year_acronym'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='examenrollmentrequest',
            unique_together=set([('student', 'offer_year_acronym')]),
        ),
    ]
