# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-06 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_enrollment', '0006_examenrollmentrequest_uniquetogether'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examenrollmentrequest',
            name='offer_year_acronym',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
