# Generated by Django 2.2.13 on 2021-10-12 07:09

from django.db import migrations, models


def migrate_fk_to_new_fields(apps, schema_editor):
    ExamEnrollmentSubmitted = apps.get_model('exam_enrollment', 'ExamEnrollmentSubmitted')
    all_exam_enrolls = ExamEnrollmentSubmitted.objects.all().select_related(
        'offer_enrollment__student',
        'offer_enrollment__education_group_year__academic_year',
        'offer_enrollment__education_group_year'
    )
    for exam_enroll in all_exam_enrolls:
        exam_enroll.program_acronym = exam_enroll.offer_enrollment.education_group_year.acronym
        exam_enroll.year = exam_enroll.offer_enrollment.education_group_year.academic_year.year
        exam_enroll.registration_id = exam_enroll.offer_enrollment.student.registration_id

    ExamEnrollmentSubmitted.objects.bulk_update(
        all_exam_enrolls,
        ['program_acronym', 'year', 'registration_id'],
        batch_size=1000
    )


class Migration(migrations.Migration):
    dependencies = [
        ('exam_enrollment', '0008_examenrollmentrequest_fetch_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='examenrollmentsubmitted',
            name='program_acronym',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='examenrollmentsubmitted',
            name='registration_id',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='examenrollmentsubmitted',
            name='year',
            field=models.IntegerField(null=True),
        ),
        migrations.RunPython(migrate_fk_to_new_fields),
        migrations.AlterField(
            model_name='examenrollmentsubmitted',
            name='program_acronym',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='examenrollmentsubmitted',
            name='registration_id',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='examenrollmentsubmitted',
            name='year',
            field=models.IntegerField(),
        ),
    ]
