# Generated by Django 2.2.13 on 2021-10-12 14:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('exam_enrollment', '0008_examenrollmentrequest_fetch_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExamEnrollmentSubmitted',
        ),
    ]
