# Generated by Django 3.2.12 on 2022-02-11 13:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('exam_enrollment', '0009_delete_examenrollmentsubmitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examenrollmentrequest',
            name='document',
            field=models.JSONField(),
        ),
    ]
