# coding: utf-8

"""
    Continuing Education API

    This API delivers data for the Continuing Education project.  # noqa: E501

    OpenAPI spec version: 0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.models.admission_get import AdmissionGet  # noqa: E501
from openapi_client.rest import ApiException


class TestAdmissionGet(unittest.TestCase):
    """AdmissionGet unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAdmissionGet(self):
        """Test AdmissionGet"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openapi_client.models.admission_get.AdmissionGet()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
