# coding: utf-8

"""
    Continuing Education API

    This API delivers data for the Continuing Education project.  # noqa: E501

    OpenAPI spec version: 0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.default_api import DefaultApi  # noqa: E501
from openapi_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_admissions_post(self):
        """Test case for admissions_post

        """
        pass

    def test_admissions_uuid_delete(self):
        """Test case for admissions_uuid_delete

        """
        pass

    def test_admissions_uuid_get(self):
        """Test case for admissions_uuid_get

        """
        pass

    def test_admissions_uuid_patch(self):
        """Test case for admissions_uuid_patch

        """
        pass

    def test_admissions_uuid_put(self):
        """Test case for admissions_uuid_put

        """
        pass

    def test_persons_details_get(self):
        """Test case for persons_details_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
