from django.utils.translation import ugettext_lazy as _

CRITERIA_1 = "CRITERIA_1"
CRITERIA_2 = "CRITERIA_2"
CRITERIA_3 = "CRITERIA_3"
CRITERIA_4 = "CRITERIA_4"
CRITERIA_5 = "CRITERIA_5"
CRITERIA_6 = "CRITERIA_6"
CRITERIA_7 = "CRITERIA_7"

POSITION_ORDER_1 = 1
POSITION_ORDER_2 = 2
POSITION_ORDER_3 = 3
POSITION_ORDER_4 = 4
POSITION_ORDER_5 = 5
POSITION_ORDER_6 = 6
POSITION_ORDER_7 = 7

ASSIMILATION_CRITERIA_CHOICES = (
    (CRITERIA_1, _(CRITERIA_1), POSITION_ORDER_1),
    (CRITERIA_2, _(CRITERIA_2), POSITION_ORDER_2),
    (CRITERIA_3, _(CRITERIA_3), POSITION_ORDER_3),
    (CRITERIA_4, _(CRITERIA_4), POSITION_ORDER_4),
    (CRITERIA_5, _(CRITERIA_5), POSITION_ORDER_5),
    (CRITERIA_6, _(CRITERIA_6), POSITION_ORDER_6),
    (CRITERIA_7, _(CRITERIA_7), POSITION_ORDER_7),
)


def find(criteria):
    for elt in ASSIMILATION_CRITERIA_CHOICES:
        if elt[0] == criteria:
            return elt
    return None
