# coding: utf-8

# flake8: noqa
"""
    Internship API

    This API delivers data for the Internship project.  # noqa: E501

    OpenAPI spec version: 1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

# import models into model package
from internship.openapi_client.models.allocation_get import AllocationGet
from internship.openapi_client.models.cohort_get import CohortGet
from internship.openapi_client.models.country import Country
from internship.openapi_client.models.internship_get import InternshipGet
from internship.openapi_client.models.master_get import MasterGet
from internship.openapi_client.models.organization_get import OrganizationGet
from internship.openapi_client.models.paging import Paging
from internship.openapi_client.models.period_get import PeriodGet
from internship.openapi_client.models.person import Person
from internship.openapi_client.models.specialty_get import SpecialtyGet
from internship.openapi_client.models.student import Student
from internship.openapi_client.models.student_affectation_get import StudentAffectationGet
from internship.openapi_client.models.student_get import StudentGet
