# coding: utf-8

"""
    Internship API

    This API delivers data for the Internship project.  # noqa: E501

    OpenAPI spec version: 1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class InternshipGet(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'uuid': 'str',
        'name': 'str',
        'speciality': 'object',
        'cohort': 'object',
        'length_in_periods': 'float',
        'position': 'float'
    }

    attribute_map = {
        'uuid': 'uuid',
        'name': 'name',
        'speciality': 'speciality',
        'cohort': 'cohort',
        'length_in_periods': 'length_in_periods',
        'position': 'position'
    }

    def __init__(self, uuid=None, name=None, speciality=None, cohort=None, length_in_periods=None, position=None):  # noqa: E501
        """InternshipGet - a model defined in OpenAPI"""  # noqa: E501

        self._uuid = None
        self._name = None
        self._speciality = None
        self._cohort = None
        self._length_in_periods = None
        self._position = None
        self.discriminator = None

        if uuid is not None:
            self.uuid = uuid
        if name is not None:
            self.name = name
        if speciality is not None:
            self.speciality = speciality
        if cohort is not None:
            self.cohort = cohort
        if length_in_periods is not None:
            self.length_in_periods = length_in_periods
        if position is not None:
            self.position = position

    @property
    def uuid(self):
        """Gets the uuid of this InternshipGet.  # noqa: E501


        :return: The uuid of this InternshipGet.  # noqa: E501
        :rtype: str
        """
        return self._uuid

    @uuid.setter
    def uuid(self, uuid):
        """Sets the uuid of this InternshipGet.


        :param uuid: The uuid of this InternshipGet.  # noqa: E501
        :type: str
        """

        self._uuid = uuid

    @property
    def name(self):
        """Gets the name of this InternshipGet.  # noqa: E501


        :return: The name of this InternshipGet.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this InternshipGet.


        :param name: The name of this InternshipGet.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def speciality(self):
        """Gets the speciality of this InternshipGet.  # noqa: E501


        :return: The speciality of this InternshipGet.  # noqa: E501
        :rtype: object
        """
        return self._speciality

    @speciality.setter
    def speciality(self, speciality):
        """Sets the speciality of this InternshipGet.


        :param speciality: The speciality of this InternshipGet.  # noqa: E501
        :type: object
        """

        self._speciality = speciality

    @property
    def cohort(self):
        """Gets the cohort of this InternshipGet.  # noqa: E501


        :return: The cohort of this InternshipGet.  # noqa: E501
        :rtype: object
        """
        return self._cohort

    @cohort.setter
    def cohort(self, cohort):
        """Sets the cohort of this InternshipGet.


        :param cohort: The cohort of this InternshipGet.  # noqa: E501
        :type: object
        """

        self._cohort = cohort

    @property
    def length_in_periods(self):
        """Gets the length_in_periods of this InternshipGet.  # noqa: E501


        :return: The length_in_periods of this InternshipGet.  # noqa: E501
        :rtype: float
        """
        return self._length_in_periods

    @length_in_periods.setter
    def length_in_periods(self, length_in_periods):
        """Sets the length_in_periods of this InternshipGet.


        :param length_in_periods: The length_in_periods of this InternshipGet.  # noqa: E501
        :type: float
        """

        self._length_in_periods = length_in_periods

    @property
    def position(self):
        """Gets the position of this InternshipGet.  # noqa: E501


        :return: The position of this InternshipGet.  # noqa: E501
        :rtype: float
        """
        return self._position

    @position.setter
    def position(self, position):
        """Sets the position of this InternshipGet.


        :param position: The position of this InternshipGet.  # noqa: E501
        :type: float
        """

        self._position = position

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InternshipGet):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
