# coding: utf-8

"""
    Continuing Education API

    This API delivers data for the Continuing Education project.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class RegistrationPostSerializer(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'address': 'AddressPostSerializer',
        'billing_address': 'AddressPostSerializer',
        'residence_address': 'AddressPostSerializer'
    }

    attribute_map = {
        'address': 'address',
        'billing_address': 'billing_address',
        'residence_address': 'residence_address'
    }

    def __init__(self, address=None, billing_address=None, residence_address=None):  # noqa: E501
        """RegistrationPostSerializer - a model defined in OpenAPI"""  # noqa: E501

        self._address = None
        self._billing_address = None
        self._residence_address = None
        self.discriminator = None

        if address is not None:
            self.address = address
        if billing_address is not None:
            self.billing_address = billing_address
        if residence_address is not None:
            self.residence_address = residence_address

    @property
    def address(self):
        """Gets the address of this RegistrationPostSerializer.  # noqa: E501


        :return: The address of this RegistrationPostSerializer.  # noqa: E501
        :rtype: AddressPostSerializer
        """
        return self._address

    @address.setter
    def address(self, address):
        """Sets the address of this RegistrationPostSerializer.


        :param address: The address of this RegistrationPostSerializer.  # noqa: E501
        :type: AddressPostSerializer
        """

        self._address = address

    @property
    def billing_address(self):
        """Gets the billing_address of this RegistrationPostSerializer.  # noqa: E501


        :return: The billing_address of this RegistrationPostSerializer.  # noqa: E501
        :rtype: AddressPostSerializer
        """
        return self._billing_address

    @billing_address.setter
    def billing_address(self, billing_address):
        """Sets the billing_address of this RegistrationPostSerializer.


        :param billing_address: The billing_address of this RegistrationPostSerializer.  # noqa: E501
        :type: AddressPostSerializer
        """

        self._billing_address = billing_address

    @property
    def residence_address(self):
        """Gets the residence_address of this RegistrationPostSerializer.  # noqa: E501


        :return: The residence_address of this RegistrationPostSerializer.  # noqa: E501
        :rtype: AddressPostSerializer
        """
        return self._residence_address

    @residence_address.setter
    def residence_address(self, residence_address):
        """Sets the residence_address of this RegistrationPostSerializer.


        :param residence_address: The residence_address of this RegistrationPostSerializer.  # noqa: E501
        :type: AddressPostSerializer
        """

        self._residence_address = residence_address

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RegistrationPostSerializer):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
