# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-26 10:51
from __future__ import unicode_literals

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0011_learningunitcomponent_coefficient_repetition'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('maximum_enrollments', models.IntegerField()),
                ('master', models.CharField(blank=True, max_length=100, null=True)),
                ('selectable', models.BooleanField(default=True)),
            ],
            options={
                'permissions': (('is_internship_manager', 'Is Internship Manager'), ('can_access_internship', 'Can access internships')),
            },
        ),
        migrations.CreateModel(
            name='InternshipSpeciality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=125)),
                ('acronym', models.CharField(max_length=125)),
                ('mandatory', models.BooleanField(default=False)),
                ('order_postion', models.IntegerField(default=0)),
                ('learning_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.LearningUnit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('acronym', models.CharField(blank=True, max_length=15)),
                ('website', models.URLField(blank=True, max_length=255, null=True)),
                ('reference', models.CharField(blank=True, max_length=30, null=True)),
                ('type', models.CharField(blank=True, default='service partner', max_length=30, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='internshipoffer',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internship.Organization'),
        ),
        migrations.AddField(
            model_name='internshipoffer',
            name='speciality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='internship.InternshipSpeciality'),
        ),
    ]
