# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-26 11:12
from __future__ import unicode_literals

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_learningunitcomponent_coefficient_repetition'),
        ('internship', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('choice', models.IntegerField()),
                ('internship_choice', models.IntegerField(default=0)),
                ('priority', models.BooleanField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internship.Organization')),
                ('speciality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='internship.InternshipSpeciality')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Student')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
