# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-04 09:54
from __future__ import unicode_literals

from django.core.management.sql import emit_post_migrate_signal
from django.db import migrations


def add_init_internship_student_group(apps, schema_editor):
    # create group
    db_alias = schema_editor.connection.alias
    emit_post_migrate_signal(2, False, db_alias)
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    internship_students_group, created = Group.objects.get_or_create(name='internship_students')


def add_users_to_internship_student_group(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    InternshipStudentInformation = apps.get_model('internship', 'InternshipStudentInformation')
    internship_students_group = Group.objects.get(name='internship_students')
    for student in InternshipStudentInformation.objects.all():
        person = student.person
        if person.user:
            user = person.user
            user.groups.add(internship_students_group)


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0008_auto_20170302_1128'),
    ]

    operations = [
        migrations.RunPython(add_init_internship_student_group),
        # disable migrations from removed models
        # migrations.RunPython(add_users_to_internship_student_group),
    ]
