# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-06 14:54
from __future__ import unicode_literals

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0010_auto_20170306_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodInternshipPlaces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('number_places', models.IntegerField(blank=None)),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internship.InternshipOffer')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internship.Period')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
