# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-27 09:00
from __future__ import unicode_literals

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0011_periodinternshipplaces'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('free_internships_number', models.IntegerField()),
                ('publication_start_date', models.DateField()),
                ('subscription_start_date', models.DateField()),
                ('subscription_end_date', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
