# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-03 08:50
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


def linkToDefaultCohort(apps, schema_editor):
    Cohort = apps.get_model("internship", "Cohort")
    Organization = apps.get_model("internship", "Organization")
    db_alias = schema_editor.connection.alias
    default_cohort = Cohort.objects.first()
    Organization.objects.all().update(cohort=default_cohort)

class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0015_cohort_student_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='cohort',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='internship.Cohort'),
            preserve_default=False,
        ),
        migrations.RunPython(linkToDefaultCohort),
        migrations.AlterField(
            model_name='organization',
            name='cohort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internship.Cohort'),
            preserve_default=False
        )
    ]
