
# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-04 14:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0022_remove_internshipspeciality_order_postion'),
    ]

    operations = [
        migrations.RunSQL("select setval('internship_internship_id_seq', 10);")
    ]
