# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-22 15:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0025_prevent_multiple_choices_for_preference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internshipmaster',
            name='organization',
        ),
        migrations.DeleteModel(
            name='InternshipMaster',
        ),
    ]
