# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-22 16:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0026_auto_20180122_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internshipoffer',
            name='internship',
        ),
    ]
