# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-22 16:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0027_remove_internshipoffer_internship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internshipspeciality',
            name='learning_unit',
        ),
    ]
