# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-22 21:51
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0007_remove_gradetype_language_exam_required'),
        ('internship', '0028_remove_internshipspeciality_learning_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internshipstudentinformation',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='internshipstudentinformation',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='type',
        ),
        migrations.AddField(
            model_name='organization',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reference.Country'),
        ),
        migrations.AddField(
            model_name='organization',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
