# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-25 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0029_auto_20180122_2251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationaddress',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='periodinternshipplaces',
            name='internship_offer',
        ),
        migrations.RemoveField(
            model_name='periodinternshipplaces',
            name='period',
        ),
        migrations.AddField(
            model_name='internshipchoice',
            name='registered',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.DeleteModel(
            name='OrganizationAddress',
        ),
        migrations.DeleteModel(
            name='PeriodInternshipPlaces',
        ),
    ]
