# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-25 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0031_auto_20180125_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipspeciality',
            name='selectable',
            field=models.BooleanField(default=True),
        ),
    ]
