# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-23 09:55
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0032_internshipspeciality_selectable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cohort',
            name='free_internships_number',
        ),
        migrations.RemoveField(
            model_name='internshipstudentaffectationstat',
            name='type_of_internship',
        ),
        migrations.AddField(
            model_name='internshipstudentaffectationstat',
            name='internship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='internship.Internship'),
        ),
        migrations.AddField(
            model_name='internshipstudentaffectationstat',
            name='type',
            field=models.CharField(choices=[('S', 'S'), ('N', 'N'), ('X', 'X')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='internshipstudentaffectationstat',
            name='choice',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('E', 'E'), ('I', 'I'), ('X', 'X')], default='0', max_length=1),
        ),
    ]
