# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-02 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0032_internshipspeciality_selectable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cohort',
            name='free_internships_number',
        ),
        migrations.AlterField(
            model_name='internshipstudentinformation',
            name='contest',
            field=models.CharField(blank=True, choices=[('SPECIALIST', 'specialist'), ('GENERALIST', 'generalist')], max_length=124, null=True),
        ),
    ]
