# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-25 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0033_auto_20180423_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipstudentinformation',
            name='contest',
            field=models.CharField(blank=True, choices=[('SPECIALIST', 'specialist'), ('GENERALIST', 'generalist')], max_length=124, null=True),
        ),
    ]
