# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-07-24 07:57
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0035_auto_20181126_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipchoice',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.Student'),
        ),
        migrations.AlterField(
            model_name='internshipstudentaffectationstat',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.Student'),
        ),
        migrations.AlterField(
            model_name='internshipstudentinformation',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.Person'),
        ),
    ]
