# Generated by Django 3.2.19 on 2023-10-26 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0088_delete_learningcontainer'),
        ('internship', '0037_internship_masters_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internship',
            name='cohort',
        ),
        migrations.RemoveField(
            model_name='internship',
            name='speciality',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='cohort',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='country',
        ),
        migrations.RemoveField(
            model_name='period',
            name='cohort',
        ),
        migrations.RemoveField(
            model_name='internshipoffer',
            name='cohort',
        ),
        migrations.RemoveField(
            model_name='internshipoffer',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='internshipspeciality',
            name='cohort',
        ),
        migrations.RemoveField(
            model_name='internshipstudentaffectationstat',
            name='internship',
        ),
        migrations.RemoveField(
            model_name='internshipstudentaffectationstat',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='internshipstudentaffectationstat',
            name='period',
        ),
        migrations.RemoveField(
            model_name='internshipstudentinformation',
            name='cohort',
        ),
        migrations.DeleteModel(
            name='Cohort',
        ),
        migrations.DeleteModel(
            name='Period',
        ),
        migrations.RemoveField(
            model_name='internshipchoice',
            name='internship',
        ),
        migrations.RemoveField(
            model_name='internshipchoice',
            name='organization',
        ),
        migrations.DeleteModel(
            name='Internship',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
