# Generated by Django 3.2.20 on 2023-10-30 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0038_auto_20231026_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internshipoffer',
            name='speciality',
        ),
        migrations.RemoveField(
            model_name='internshipstudentaffectationstat',
            name='speciality',
        ),
        migrations.RemoveField(
            model_name='internshipstudentaffectationstat',
            name='student',
        ),
        migrations.RemoveField(
            model_name='internshipstudentinformation',
            name='person',
        ),
        migrations.DeleteModel(
            name='InternshipChoice',
        ),
        migrations.DeleteModel(
            name='InternshipOffer',
        ),
        migrations.DeleteModel(
            name='InternshipSpeciality',
        ),
        migrations.DeleteModel(
            name='InternshipStudentAffectationStat',
        ),
        migrations.DeleteModel(
            name='InternshipStudentInformation',
        ),
    ]
