# Generated by Django 3.2.20 on 2023-10-30 09:39

from django.db import migrations
from django.db.migrations import RunPython


def move_permission_to_person(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    Permission.objects.filter(codename='can_access_internship', content_type__model='internshipoffer').delete()

    base_person_content_type = ContentType.objects.get(app_label='base', model='person')
    internship_students_group, group_created = Group.objects.get_or_create(name='internship_students')
    can_access_internship_perm_person, created = Permission.objects.get_or_create(codename='can_access_internship', name='Can access internship', content_type=base_person_content_type)

    internship_students_group.permissions.add(can_access_internship_perm_person)

    internship_masters_group, created = Group.objects.get_or_create(name='internship_masters')
    internship_masters_group.permissions.add(can_access_internship_perm_person)


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0039_auto_20231030_1039'),
    ]

    operations = [
        migrations.RunPython(move_permission_to_person, reverse_code=RunPython.noop),
    ]
