# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-28 08:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admission', '0002_auto_20160715_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferProposition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acronym', models.CharField(max_length=200)),
                ('student_can_manage_readers', models.BooleanField(default=True)),
                ('readers_visibility_date_for_students', models.BooleanField(default=False)),
                ('adviser_can_suggest_reader', models.BooleanField(default=False)),
                ('evaluation_first_year', models.BooleanField(default=False)),
                ('validation_commission_exists', models.BooleanField(default=False)),
                ('start_visibility_proposition', models.DateField(default=django.utils.timezone.now)),
                ('end_visibility_proposition', models.DateField(default=django.utils.timezone.now)),
                ('start_visibility_dissertation', models.DateField(default=django.utils.timezone.now)),
                ('end_visibility_dissertation', models.DateField(default=django.utils.timezone.now)),
                ('offer_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.OfferYear')),
            ],
        ),
    ]
