# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-09 10:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dissertation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerproposition',
            name='end_edit_title',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='offerproposition',
            name='end_jury_visibility',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='offerproposition',
            name='start_edit_title',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='offerproposition',
            name='start_jury_visibility',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
