# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-06 14:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20160906_1451'),
        ('dissertation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerproposition',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Offer'),
        ),
    ]
