# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-05 09:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_offerenrollment'),
        ('dissertation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offerproposition',
            name='offer_year',
        ),
        migrations.AddField(
            model_name='offerproposition',
            name='offer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='base.Offer'),
            preserve_default=False,
        ),
    ]
