# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-09 13:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dissertation', '0002_auto_20160909_1003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offerproposition',
            name='readers_visibility_date_for_students',
        ),
    ]
