# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-06 14:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dissertation', '0002_auto_20160905_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerproposition',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Offer'),
        ),
    ]
