# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-09 15:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dissertation', '0003_remove_offerproposition_readers_visibility_date_for_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dissertation',
            name='defend_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.AcademicYear'),
        ),
        migrations.AlterField(
            model_name='dissertation',
            name='offer_year_start',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.OfferYear'),
        ),
    ]
