# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-06 15:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dissertation', '0003_propositiondocumentfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='DissertationLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='dissertation',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dissertation.DissertationLocation'),
        ),
    ]
