# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-10 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dissertation', '0007_remove_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dissertation',
            name='defend_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propositiondissertation',
            name='level',
            field=models.CharField(choices=[('SPECIFIC', 'specific_subject'), ('THEME', 'large_theme')], default='DOMAIN', max_length=12),
        ),
        migrations.AlterField(
            model_name='propositiondissertation',
            name='type',
            field=models.CharField(choices=[('RDL', 'litterature_review'), ('EMP', 'empirical_research'), ('THE', 'theoretical_analysis'), ('PRO', 'project_dissertation'), ('DEV', 'development_dissertation'), ('OTH', 'other')], default='RDL', max_length=12),
        ),
    ]
