# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-11 10:25
from __future__ import unicode_literals

from django.db import migrations
from django.db import connection


def dictfetchall(cursor):
    "Return all rows from a cursor as a dict"
    columns = [col[0] for col in cursor.description]
    return [
        dict(zip(columns, row))
        for row in cursor.fetchall()
        ]


def my_custom_sql():
    cursor = connection.cursor()
    cursor.execute("select * from dissertation_propositiondissertation_offer_proposition")
    for record in dictfetchall(cursor):
        print(record)
        propositiondissertation_id = record['propositiondissertation_id']
        offerproposition_id = record['offerproposition_id']


class Migration(migrations.Migration):

    dependencies = [
        ('dissertation', '0007_propositionoffer'),
    ]

    operations = [
        migrations.RunPython(my_custom_sql),
        migrations.RemoveField(
            model_name='propositiondissertation',
            name='offer_proposition',
        ),
    ]
