# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-10 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dissertation', '0015_dissertation_defend_period_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dissertation',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
