# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-10 13:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dissertation', '0016_auto_20170410_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferPropositionGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name_short', models.CharField(max_length=10)),
                ('name_long', models.CharField(max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='offerproposition',
            name='offer_proposition_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dissertation.OfferPropositionGroup'),
        ),
    ]
