# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-01 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dissertation', '0017_auto_20171010_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerproposition',
            name='global_email_to_commission',
            field=models.BooleanField(default=False),
        ),
    ]
