# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_code', models.CharField(max_length=2, unique=True)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('nationality', models.CharField(blank=True, max_length=80, null=True)),
                ('european_union', models.BooleanField(default=False)),
                ('dialing_code', models.CharField(blank=True, max_length=3, null=True)),
                ('cref_code', models.CharField(blank=True, max_length=3, null=True)),
            ],
        ),
    ]
