# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-10 09:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssimilationCriteria',
        ),
    ]
