# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-19 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionExamType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('adhoc', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EducationInstitution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('institution_type', models.CharField(choices=[('SECONDARY', 'Secondaire'), ('UNIVERSITY', 'University')], max_length=20)),
                ('postal_code', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=255)),
                ('national_community', models.CharField(blank=True, choices=[('FRENCH', 'Communauté française de Belgique'), ('GERMAN', 'Communauté germanophone'), ('DUTCH', 'Communauté flamande')], max_length=20, null=True)),
                ('adhoc', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EducationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('TRANSITION', 'Transition'), ('QUALIFICATION', 'Qualification'), ('ANOTHER', 'Autre')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('adhoc', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, unique=True)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('recognized', models.BooleanField(default=False)),
            ],
        ),
    ]
