# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-19 08:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0002_admissionexamtype_educationinstitution_educationtype_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationinstitution',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reference.Country'),
        ),
    ]
