# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-10 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0002_delete_assimilationcriteria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradetype',
            name='institutional_grade_type',
            field=models.CharField(blank=True, choices=[('BACHELOR', 'BACHELOR'), ('MASTER_60', 'MASTER_60'), ('MASTER_120', 'MASTER_120'), ('MASTER_180_OR_240', 'MASTER_180_OR_240'), ('ADVANCED_MASTER', 'ADVANCED_MASTER'), ('TRAINING_CERTIFICATE', 'TRAINING_CERTIFICATE'), ('CERTIFICATE', 'CERTIFICATE'), ('DOCTORATE', 'DOCTORATE'), ('CAPAES', 'CAPAES')], max_length=25, null=True),
        ),
        migrations.DeleteModel(
            name='InstitutionalGradeType',
        ),
    ]
