# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-20 07:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0005_educationinstitution_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationinstitution',
            name='country',
        ),
        migrations.DeleteModel(
            name='EducationType',
        ),
        migrations.DeleteModel(
            name='EducationInstitution',
        ),
    ]
