# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-27 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0007_remove_gradetype_language_exam_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domain',
            name='reference',
        ),
        migrations.AddField(
            model_name='domain',
            name='code',
            field=models.CharField(default='', max_length=50, verbose_name='code'),
            preserve_default=False,
        ),
    ]
