# Generated by Django 3.2.24 on 2024-02-23 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0011_auto_20220119_1453'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Language',
        ),
    ]
