# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-21 17:50
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPerformance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_id', models.CharField(max_length=10)),
                ('academic_year', models.IntegerField()),
                ('acronym', models.CharField(max_length=15)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('update_date', models.DateTimeField()),
                ('creation_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='studentperformance',
            unique_together=set([('registration_id', 'academic_year', 'acronym')]),
        ),
    ]
