# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-27 14:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentperformance',
            name='creation_date',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 10, 27, 14, 38, 40, 738365)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentperformance',
            name='update_date',
            field=models.DateField(default=datetime.date(2016, 10, 27)),
            preserve_default=False,
        ),
    ]
