# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-17 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentperformance',
            name='registration_id',
            field=models.CharField(db_index=True, max_length=10),
        ),
    ]
