# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-13 16:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentperformance',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2016, 10, 13, 16, 28, 13, 980260, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
