# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-03 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0002_add_index_to_student_performence'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentperformance',
            name='authorized',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='studentperformance',
            name='offer_registration_state',
            field=models.CharField(choices=[('INSCRIT', 'INSCRIT'), ('CYCLE', 'CYCLE'), ('CONDITION', 'CONDITION'), ('CESSATION', 'CESSATION')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studentperformance',
            name='creation_date',
            field=models.DateTimeField(),
        ),
    ]
