# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-17 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0003_auto_20170203_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentperformance',
            name='session_locked',
            field=models.CharField(choices=[('JANUARY', 'JANUARY'), ('JUNE', 'JUNE'), ('SEPTEMBER', 'SEPTEMBER')], max_length=50, null=True),
        ),
    ]
