# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-13 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0004_studentperformance_session_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentperformance',
            name='courses_registration_validated',
            field=models.NullBooleanField(),
        ),
    ]
