# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-03-13 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0006_studentperformance_learning_units_outside_catalog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentperformance',
            name='session_locked',
            field=models.CharField(choices=[('JANUARY', 'January'), ('JUNE', 'June'), ('SEPTEMBER', 'September')], max_length=50, null=True),
        ),
    ]
