# Generated by Django 2.2.10 on 2020-06-07 14:54

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0008_studentperformance_course_registration_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentperformance',
            name='on_site_exams_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
