# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-08-06 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0008_studentperformance_course_registration_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentperformance',
            name='course_registration_message',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
