# Generated by Django 3.2.12 on 2022-02-11 13:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('performance', '0009_studentperformance_on_site_exams_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentperformance',
            name='courses_registration_validated',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='studentperformance',
            name='data',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='studentperformance',
            name='learning_units_outside_catalog',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='studentperformance',
            name='on_site_exams_info',
            field=models.JSONField(null=True),
        ),
    ]
