# Generated by Django 3.2.12 on 2022-03-28 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0010_auto_20220301_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentperformance',
            name='data',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='studentperformance',
            name='on_site_exams_info',
            field=models.JSONField(null=True),
        ),
    ]
