# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-15 14:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_scoreencoding_uuid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScoreEncoding',
        ),
    ]
