= OSIS Portal Technical Manual
Hildeberto Mendonça, PhD
v0.1, 2016-04-16
:toc: right

The installation of OSIS-Portal is very similar to https://github.com/uclouvain/osis/blob/dev/doc/technical-manual.adoc[OSIS]. This document focus on the differences to minimize repetition.

== Installing OSIS-Portal

=== Creating the Database

Follow the steps below to create the frontend database:

    $ createdb osis_portal_local
    $ createuser osis_portal -P   // Inform the password 'osis' when asked for.
    $ psql -d osis_portal_local
      =# grant connect on database osis_portal_local to osis_portal;
      =# revoke connect on database osis_portal_local from public;
      =# alter user osis_portal createdb;
      =# \q

=== Installing and Configuring the Application

The repository `osis-portal` is a Django application. To clone the repository, execute the following commands:

    $ cd ~/python/projects/osis
    $ git clone https://github.com/uclouvain/osis-portal.git

The dependencies of OSIS-Portal are different from OSIS. That's why it deserves its own virtual environment:

    $ cd osis-portal
    $ python3 -m venv venv
    $ source venv/bin/activate
    (venv)$ pip install -r requirements.txt

Create a `.env` file based on `.env.example`:

    (venv)$ cp .env.example .env

Create the data structure in the database:

    (venv)$ python manage.py migrate

To create the super user:

    (venv)$ python manage.py createsuperuser
       Username (leave blank to use '[linux-user]'):
       Email address: your@emailaddress.com
       Password:
       Password (again):
       Superuser created successfully.

You will need this user to login on OSIS-Portal for the first time and be able to create other users.

Now, we can run the application:

    (venv)$ python manage.py runserver

You can leave the server running while you are developing. It will take into account all changes in your code, except the changes in the model. When we have finished your daily work, we can deactivate the virtual environment:

    (venv)$ deactivate

== Integrating OSIS and OSIS-Portal

OSIS and OSIS-Portal are two Django projects highly decoupled from each other, to the point where one is fully functional without the other. This is possible because both are integrated in a pure data level exchange using RabbitMQ, a message broker for asynchronous messaging.

=== Installing RabbitMQ

The installation of RabbitMQ is pretty straightforward. Just run the following command:

    $ sudo apt-get install rabbitmq-server

After the installation, RabbitMQ is immediately up and running. To check its status, run:

    $ sudo rabbitmqctl status

In case you need to stop the service for any reason, run:

    $ sudo rabbitmqctl stop

To start the service is a bit different:

    $ sudo invoke-rc.d rabbitmq-server start

At this point, RabbitMQ is ready for exchanging messages between OSIS and OSIS-Portal for development purposes, but it is difficult to visualize what is going on when you are debugging the application, since RabbitMQ is just a service running in the background. To address this issue, we can install the management console plugin:

    $ sudo rabbitmq-plugins enable rabbitmq_management

To access the management console, visit http://localhost:15672/ and inform `guest` as username and password.

=== Configuring OSIS for Message Exchanging

To enforce the principle of decoupling, OSIS and OSIS-Portal are configured to ignore the broker by default. When necessary, the access to the broker can be activated by changing the configuration of the projects. On the OSIS side, go to backoffice/queue and create the file `dev.py` based on `dev.example`:

    $ cd ~/python/projects/osis/osis/backoffice/settings
    $ cp dev.example dev.py

In the file `dev.py`, uncomment the constant `QUEUES` and its value. Then, open the `.env` file, uncomment the constant `DJANGO_SETTINGS_MODULE` and change its value to `backoffice.settings.dev`.

Finally, install the development dependencies:

    $ pip install -r dev-requirements.txt

=== Running OSIS and OSIS-Portal at the Same Time

After activating the use of the queue, it is important to keep OSIS and OSIS-Portal running at the same time, otherwise lots of messages will be accumulated in the broker because one of the apps is pushing messages while the other one is not consuming them. But to run both on the same machine (common in developer's machine), it is necessary to have different TCP/IP ports. This is configurable when launching the application. First, let's launch OSIS:

    $ cd ~/python/projects/osis/osis
    $ source venv/bin/activate
    (venv)$ python manage.py runserver

OSIS is now running in the default port 8000. Let's launch OSIS-Portal in another port to avoid conflict. Open another console window and execute:

    $ cd ~/python/projects/osis/osis-portal
    $ source venv/bin/activate
    (venv)$ python manage.py runserver 8001
