# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-08 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attribution', '0002_auto_20161208_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribution',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attribution',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
