# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-19 15:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attribution', '0002_auto_20170112_1419'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutorapplication',
            options={'permissions': (('can_access_attribution_application', 'Can access attribution application'),)},
        ),
    ]
