# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-23 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attribution', '0003_auto_20170119_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribution',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='attribution',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='tutorapplication',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='tutorapplication',
            name='start_date',
        ),
        migrations.AddField(
            model_name='attribution',
            name='end_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attribution',
            name='start_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
