# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-28 07:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attribution', '0007_tutorapplication_uuid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attribution',
            options={'permissions': (('can_access_attribution', 'Can access attribution'),)},
        ),
    ]
