# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-25 14:14
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attribution', '0010_attributionnew'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributionnew',
            name='applications',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='attributionnew',
            name='attributions',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
