# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-09 06:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attribution', '0011_auto_20171025_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationcharge',
            name='learning_unit_component',
        ),
        migrations.RemoveField(
            model_name='applicationcharge',
            name='tutor_application',
        ),
        migrations.RemoveField(
            model_name='tutorapplication',
            name='learning_unit_year',
        ),
        migrations.RemoveField(
            model_name='tutorapplication',
            name='tutor',
        ),
        migrations.AlterModelOptions(
            name='attributionnew',
            options={'permissions': (('can_access_attribution_application', 'Can access attribution application'),)},
        ),
        migrations.DeleteModel(
            name='ApplicationCharge',
        ),
        migrations.DeleteModel(
            name='TutorApplication',
        ),
    ]
