# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-03 08:43
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attribution', '0012_auto_20171109_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributionnew',
            name='applications',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='attributionnew',
            name='attributions',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list),
        ),
    ]
