# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-05 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attribution', '0013_auto_20180103_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribution',
            name='summary_responsible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attributionnew',
            name='summary_responsible',
            field=models.BooleanField(default=False),
        ),
    ]
