# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-16 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attribution', '0014_summary_responsible'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribution',
            name='deleted_new',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
    ]
