# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-16 10:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attribution', '0016_auto_20180116_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribution',
            name='deleted',
        ),
    ]
