# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-16 10:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attribution', '0017_remove_attribution_deleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attribution',
            old_name='deleted_new',
            new_name='deleted',
        ),
    ]
