# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-17 12:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attribution', '0018_auto_20180116_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attributioncharge',
            name='attribution',
        ),
        migrations.RemoveField(
            model_name='attributioncharge',
            name='learning_unit_component',
        ),
        migrations.DeleteModel(
            name='AttributionCharge',
        ),
    ]
