# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-28 11:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attribution', '0020_auto_20180328_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribution',
            name='deleted',
        ),
    ]
