# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-21 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attribution', '0021_remove_attribution_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribution',
            name='function',
            field=models.CharField(blank=True, choices=[('COORDINATOR', 'Coordinator'), ('HOLDER', 'Holder'), ('CO_HOLDER', 'Co-holder'), ('DEPUTY', 'Deputy'), ('DEPUTY_AUTHORITY', 'Deputy authority'), ('DEPUTY_SABBATICAL', 'Deputy sabbatical'), ('DEPUTY_TEMPORARY', 'Deputy temporary'), ('PROFESSOR', 'Professor'), ('INTERNSHIP_SUPERVISOR', 'Internship supervisor'), ('INTERNSHIP_CO_SUPERVISOR', 'Internship co-supervisor')], db_index=True, max_length=35, null=True),
        ),
    ]
