# Generated by Django 2.2.13 on 2021-03-04 12:38

from django.db import migrations


def remove_attribution_permissions(apps, schema_editor):
    Permission = apps.get_model('auth.Permission')
    Permission.objects.filter(codename='can_access_attribution').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('attribution', '0023_auto_20190723_1137'),
    ]

    operations = [
        migrations.RunPython(remove_attribution_permissions, migrations.RunPython.noop),
        migrations.AlterModelOptions(
            name='attributionnew',
            options={'permissions': (('can_access_attribution_application', 'Can access attribution application'), ('can_access_attribution', 'Can access attribution'))},
        ),
        migrations.DeleteModel(
            name='Attribution',
        ),
    ]
