# Generated by Django 2.2.13 on 2021-06-15 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attribution', '0024_auto_20210304_1338'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AttributionNew',
        ),
    ]
