# Generated by Django 2.2.13 on 2021-09-17 11:50

from django.db import migrations


def remove_attributionnew_permissions(apps, schema_editor):
    Permission = apps.get_model('auth.Permission')
    Permission.objects.filter(
        content_type__model="attributionnew"
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('attribution', '0025_delete_attributionnew'),
    ]

    operations = [
        migrations.RunPython(remove_attributionnew_permissions, migrations.RunPython.noop),
    ]
