# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-13 10:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0010_add_users_to_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('maximum_enrollments', models.IntegerField()),
                ('master', models.CharField(blank=True, max_length=100, null=True)),
                ('selectable', models.BooleanField(default=True)),
            ],
            options={
                'permissions': (('is_internship_manager', 'Is Internship Manager'), ('can_access_internship', 'Can access internships')),
            },
        ),
        migrations.CreateModel(
            name='InternshipSpeciality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('acronym', models.CharField(max_length=125)),
                ('mandatory', models.BooleanField(default=False)),
                ('order_postion', models.IntegerField(default=0)),
                ('learning_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.LearningUnit')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('acronym', models.CharField(blank=True, max_length=15)),
                ('website', models.URLField(blank=True, max_length=255, null=True)),
                ('reference', models.CharField(blank=True, max_length=30, null=True)),
                ('type', models.CharField(blank=True, default='service partner', max_length=30, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='internshipoffer',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internship.Organization'),
        ),
        migrations.AddField(
            model_name='internshipoffer',
            name='speciality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='internship.InternshipSpeciality'),
        ),
    ]
