# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-21 14:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0003_organizationaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('reference', models.CharField(blank=True, max_length=50, null=True)),
                ('civility', models.CharField(blank=True, choices=[('PROFESSOR', 'Professor'), ('DOCTOR', 'Doctor')], max_length=50, null=True)),
                ('type_mastery', models.CharField(blank=True, choices=[('SPECIALIST', 'Specialist'), ('GENERALIST', 'Generalist')], max_length=50, null=True)),
                ('speciality', models.CharField(blank=True, max_length=50, null=True)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='internship.Organization')),
            ],
        ),
    ]
