# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-01 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0005_auto_20170226_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipmaster',
            name='civility',
            field=models.CharField(blank=True, choices=[('PROFESSOR', 'PROFESSOR'), ('DOCTOR', 'DOCTOR')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='internshipmaster',
            name='type_mastery',
            field=models.CharField(blank=True, choices=[('SPECIALIST', 'SPECIALIST'), ('GENERALIST', 'GENERALIST')], max_length=50, null=True),
        ),
    ]
