# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-23 14:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_learningunitcomponent_coefficient_repetition'),
        ('internship', '0005_internshipstudentinformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipStudentAffectationStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(default='0', max_length=1)),
                ('cost', models.IntegerField()),
                ('consecutive_month', models.BooleanField(default=False)),
                ('type_of_internship', models.CharField(default='N', max_length=1)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internship.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='internshipstudentaffectationstat',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internship.Period'),
        ),
        migrations.AddField(
            model_name='internshipstudentaffectationstat',
            name='speciality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internship.InternshipSpeciality'),
        ),
        migrations.AddField(
            model_name='internshipstudentaffectationstat',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Student'),
        ),
    ]
