# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-06 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0009_internship_student_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipstudentinformation',
            name='contest',
            field=models.CharField(choices=[('SPECIALIST', 'specialist'), ('GENERALIST', 'generalist')], default='GENERALIST', max_length=124),
        ),
    ]
