# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-27 09:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
from internship.models import cohort


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0012_cohort'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipoffer',
            name='cohort',
            field=models.ForeignKey(default=cohort.Cohort.objects.first().pk, on_delete=django.db.models.deletion.CASCADE, to='internship.Cohort'),
            preserve_default=False,
        ),
    ]
