# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-27 11:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_learningunitcomponent_coefficient_repetition'),
        ('internship', '0015_cohortperson'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CohortPerson',
            new_name='CohortStudent',
        ),
        migrations.RemoveField(
            model_name='cohortstudent',
            name='person',
        ),
        migrations.AddField(
            model_name='cohortstudent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Student'),
            preserve_default=False,
        ),
    ]
