# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-03 13:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0017_internshipspeciality_cohort'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cohort',
            name='mandatory_internships_number',
        ),
    ]
