# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-04 14:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0019_auto_20170404_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipoffer',
            name='internship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='internship.Internship'),
        ),
    ]
