# coding: utf-8

# flake8: noqa
"""
    Continuing Education API

    This API delivers data for the Continuing Education project.  # noqa: E501

    OpenAPI spec version: 0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

# import models into model package
from openapi_client.models.address_get import AddressGet
from openapi_client.models.admission_get import AdmissionGet
from openapi_client.models.admission_post_put_patch import AdmissionPostPutPatch
from openapi_client.models.adress_post_put_patch import AdressPostPutPatch
from openapi_client.models.formation_basic_get import FormationBasicGet
from openapi_client.models.inline_response200 import InlineResponse200
from openapi_client.models.person_basic import PersonBasic
from openapi_client.models.person_get import PersonGet
from openapi_client.models.state_enum import StateEnum
