# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-07 15:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_id', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='BasePerson',
            new_name='Person',
        ),
        migrations.AddField(
            model_name='student',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Person'),
        ),
    ]
