# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-20 21:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20160707_1550'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'permissions': (('is_tutor', 'Is tutor'), ('is_student', 'Is student'), ('is_administrator', 'Is administrator'))},
        ),
    ]
