# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-11 12:53
from __future__ import unicode_literals
from django.core.management.sql import emit_post_migrate_signal

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_tutor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'permissions': (('is_tutor', 'Is tutor'), ('is_student', 'Is student'), ('is_administrator', 'Is administrator'), ('is_faculty_administrator', 'Is faculty administrator'), ('can_access_administration', 'Can access administration'))},
        ),
    ]
