# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-11 12:53
from __future__ import unicode_literals
from django.core.management.sql import emit_post_migrate_signal

from django.db import migrations


def add_faculty_administrators_group(apps, schema_editor):
    # create group
    db_alias = schema_editor.connection.alias
    emit_post_migrate_signal(2, False, db_alias)
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    faculty_administrators_group, created = Group.objects.get_or_create(name='faculty_administrators')
    if created:
        # Add permissions to group
        is_faculty_administrator = Permission.objects.get(codename='is_faculty_administrator')
        faculty_administrators_group.permissions.add(is_faculty_administrator)


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_tutor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'permissions': (('is_tutor', 'Is tutor'), ('is_student', 'Is student'), ('is_administrator', 'Is administrator'), ('is_faculty_administrator', 'Is faculty administrator'))},
        ),
    ]
