# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-02 12:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20161202_1247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learningunitcomponent',
            old_name='type',
            new_name='component_type',
        ),
    ]
