# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-02 12:57
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20161202_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningunitcomponent',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='learningunityear',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
