# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-02 13:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20161202_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningunitcomponent',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='learningunityear',
            name='uuid',
        ),
    ]
