# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-06 12:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_offerenrollment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(max_length=255)),
                ('acronym', models.CharField(max_length=15)),
                ('website', models.URLField(blank=True, max_length=255, null=True)),
                ('reference', models.CharField(blank=True, max_length=30, null=True)),
                ('type', models.CharField(blank=True, choices=[('MAIN', 'MAIN'), ('ACADEMIC_PARTNER', 'ACADEMIC_PARTNER'), ('INDUSTRIAL_PARTNER', 'INDUSTRIAL_PARTNER'), ('SERVICE_PARTNER', 'SERVICE_PARTNER'), ('COMMERCE_PARTNER', 'COMMERCE_PARTNER'), ('PUBLIC_PARTNER', 'PUBLIC_PARTNER')], default='UNKNOWN', max_length=30, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='campus',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Organization'),
        ),
    ]
