# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-06 14:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_offerenrollment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='changed',
        ),
        migrations.RemoveField(
            model_name='offerenrollment',
            name='changed',
        ),
    ]
