# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-08 12:18
from __future__ import unicode_literals
from django.contrib.auth.models import Group, User

from django.db import migrations
import base.models as mdl


def add_users_to_group(apps, schema_editor):
    tutors_group = Group.objects.get(name='tutors')
    students_group = Group.objects.get(name='students')
    for user in list(User.objects.all()):
        person = mdl.person.find_by_user(user)
        if person:
            # Check Tutor
            if mdl.tutor.find_by_person(person) and tutors_group:
                user.groups.add(tutors_group)
            # Check Student
            if mdl.student.find_by_person(person) and students_group:
                user.groups.add(students_group)


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_modif_user_last_name_lenght'),
    ]

    operations = [
    ]