# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-02 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20161202_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningunitcomponent',
            name='component_type',
            field=models.CharField(blank=True, choices=[('LECTURING', 'LECTURING'), ('PRACTICAL_EXERCISES', 'PRACTICAL_EXERCISES')], db_index=True, max_length=25, null=True),
        ),
    ]
