# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-02 13:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20161202_1332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learningunitcomponent',
            old_name='component_type',
            new_name='type',
        ),
    ]
