# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-04 13:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_learningunitcomponent_coefficient_repetition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offeryear',
            name='subject_to_quota',
        ),
    ]
