# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-05 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20161202_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningunityear',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
