# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-30 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_offeryear_subject_to_quota'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='reference',
            new_name='acronym_learning_unit',
        ),
        migrations.AddField(
            model_name='organization',
            name='changed',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='acronym',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
