# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-05 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_learningunityear_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningunityear',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
