# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-07 11:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_auto_20170530_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='national_id',
        ),
    ]
