# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-16 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_remove_person_national_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerenrollment',
            name='enrollment_state',
            field=models.CharField(blank=True, choices=[('SUBSCRIBED', 'SUBSCRIBED'), ('PROVISORY', 'PROVISORY')], max_length=15, null=True),
        ),
    ]
