# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-18 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_offerenrollment_enrollment_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='campus',
            name='code',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='campus',
            name='is_administration',
            field=models.BooleanField(default=False),
        ),
    ]
