# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-20 09:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_student_academic_enrollment_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='academic_enrollment_state',
        ),
    ]
