# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-27 13:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_auto_20171025_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningComponentYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('external_id', models.CharField(blank=True, max_length=100, null=True)),
                ('changed', models.DateTimeField(auto_now=True, null=True)),
                ('acronym', models.CharField(blank=True, max_length=4, null=True)),
                ('type', models.CharField(blank=True, choices=[('LECTURING', 'LECTURING'), ('PRACTICAL_EXERCISES', 'PRACTICAL_EXERCISES')], db_index=True, max_length=30, null=True)),
                ('volume_declared_vacant', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LearningContainerYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('external_id', models.CharField(blank=True, max_length=100, null=True)),
                ('changed', models.DateTimeField(auto_now=True, null=True)),
                ('acronym', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('title_english', models.CharField(blank=True, max_length=250, null=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.AcademicYear')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='learningcomponentyear',
            name='learning_container_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.LearningContainerYear'),
        ),
        migrations.AddField(
            model_name='learningunitcomponent',
            name='learning_component_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.LearningComponentYear'),
        ),
    ]
