# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-02 16:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_auto_20171027_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningunityear',
            name='in_charge',
        ),
        migrations.RemoveField(
            model_name='learningunityear',
            name='team',
        ),
        migrations.RemoveField(
            model_name='learningunityear',
            name='vacant',
        ),
        migrations.AddField(
            model_name='learningcontaineryear',
            name='in_charge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='learningcontaineryear',
            name='is_vacant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='learningcontaineryear',
            name='team',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='learningcontaineryear',
            name='type_declaration_vacant',
            field=models.CharField(blank=True, choices=[('RESEVED_FOR_INTERNS', 'RESEVED_FOR_INTERNS'), ('OPEN_FOR_EXTERNS', 'OPEN_FOR_EXTERNS'), ('EXCEPTIONAL_PROCEDURE', 'EXCEPTIONAL_PROCEDURE'), ('VACANT_NOT_PUBLISH', 'VACANT_NOT_PUBLISH'), ('DO_NOT_ASSIGN', 'DO_NOT_ASSIGN')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='learningunityear',
            name='learning_container_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.LearningContainerYear'),
        ),
    ]
