# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-15 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_auto_20171103_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningunityear',
            name='subtype',
            field=models.CharField(blank=True, choices=[('FULL', 'FULL'), ('PARTIM', 'PARTIM')], max_length=50, null=True),
        ),
    ]
