# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-30 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_learningunityear_subtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningunitenrollment',
            name='enrollment_state',
            field=models.CharField(blank=True, choices=[('ENROLLED', 'ENROLLED')], max_length=20, null=True),
        ),
    ]
