# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-01 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_learningunitenrollment_enrollment_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningunitenrollment',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
