# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-08 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_learningunitenrollment_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningcomponentyear',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='learningcontainer',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='learningcontaineryear',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='learningunit',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='learningunitcomponent',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='learningunityear',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='offerenrollment',
            name='enrollment_state',
            field=models.CharField(blank=True, choices=[('SUBSCRIBED', 'SUBSCRIBED'), ('PROVISORY', 'PROVISORY'), ('PENDING', 'PENDING'), ('TERMINATION', 'TERMINATION'), ('END_OF_CYCLE', 'END_OF_CYCLE')], max_length=15, null=True),
        ),
    ]
