# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-22 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_auto_20171213_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='entityversion',
            name='acronym',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
    ]
