# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-22 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_auto_20171213_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='entityversion',
            name='acronym',
            field=models.CharField(db_index=True, default=None, max_length=20),
        ),
    ]
