# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-16 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_entityversion_acronym'),
    ]

    operations = [
        migrations.AddField(
            model_name='entitycomponentyear',
            name='deleted_new',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='entitycontaineryear',
            name='deleted_new',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='learningcomponentyear',
            name='deleted_new',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='learningcontainer',
            name='deleted_new',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='learningcontaineryear',
            name='deleted_new',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='learningunit',
            name='deleted_new',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='learningunitcomponent',
            name='deleted_new',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='learningunitenrollment',
            name='deleted_new',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='learningunityear',
            name='deleted_new',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
    ]
