# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-16 10:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_auto_20180116_1145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entitycomponentyear',
            old_name='deleted_new',
            new_name='deleted',
        ),
        migrations.RenameField(
            model_name='entitycontaineryear',
            old_name='deleted_new',
            new_name='deleted',
        ),
        migrations.RenameField(
            model_name='learningcomponentyear',
            old_name='deleted_new',
            new_name='deleted',
        ),
        migrations.RenameField(
            model_name='learningcontainer',
            old_name='deleted_new',
            new_name='deleted',
        ),
        migrations.RenameField(
            model_name='learningcontaineryear',
            old_name='deleted_new',
            new_name='deleted',
        ),
        migrations.RenameField(
            model_name='learningunit',
            old_name='deleted_new',
            new_name='deleted',
        ),
        migrations.RenameField(
            model_name='learningunitcomponent',
            old_name='deleted_new',
            new_name='deleted',
        ),
        migrations.RenameField(
            model_name='learningunitenrollment',
            old_name='deleted_new',
            new_name='deleted',
        ),
        migrations.RenameField(
            model_name='learningunityear',
            old_name='deleted_new',
            new_name='deleted',
        ),
    ]
