# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-02 15:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_auto_20180116_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entitycomponentyear',
            name='hourly_volume_partial',
        ),
    ]
