# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-02 15:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_auto_20180116_1146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entitycomponentyear',
            old_name='hourly_volume_partial',
            new_name='repartition_volume',
        ),
        migrations.RemoveField(
            model_name='entitycomponentyear',
            name='hourly_volume_total',
        ),
    ]
