# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-02 15:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_remove_entitycomponentyear_hourly_volume_partial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entitycomponentyear',
            old_name='hourly_volume_total',
            new_name='repartition_volume',
        ),
    ]
