# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-02 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_rename_title_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningunityear',
            name='specific_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
