# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-28 11:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_auto_20180312_0913'),
    ]

    operations = [
        # Remove all deleted records physically
        migrations.RunSQL("DELETE FROM base_learningunitcomponent CASCADE WHERE deleted is not null"),
        migrations.RunSQL("DELETE FROM base_entitycomponentyear CASCADE WHERE deleted is not null"),
        migrations.RunSQL("DELETE FROM base_entitycontaineryear CASCADE WHERE deleted is not null"),
        migrations.RunSQL("DELETE FROM base_learningcomponentyear CASCADE WHERE deleted is not null"),
        migrations.RunSQL("DELETE FROM base_learningunityear CASCADE WHERE deleted is not null"),
        migrations.RunSQL("DELETE FROM base_learningunit CASCADE WHERE deleted is not null"),
        migrations.RunSQL("DELETE FROM base_learningcontaineryear CASCADE WHERE deleted is not null"),
        migrations.RunSQL("DELETE FROM base_learningcontainer CASCADE WHERE deleted is not null"),
    ]
