# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-17 11:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_auto_20180328_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningunit',
            name='acronym',
        ),
        migrations.RemoveField(
            model_name='learningunit',
            name='description',
        ),
        migrations.RemoveField(
            model_name='learningunit',
            name='title',
        ),
    ]
