# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-13 13:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0039_auto_20180606_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningunitcomponent',
            name='duration',
        ),
    ]
