# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-17 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0040_remove_learningunitcomponent_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningunitenrollment',
            name='enrollment_state',
            field=models.CharField(choices=[('ENROLLED', 'ENROLLED')], default='', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='learningunitenrollment',
            unique_together=set([('offer_enrollment', 'learning_unit_year', 'enrollment_state')]),
        ),
    ]
