# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-19 12:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0042_auto_20181019_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('start_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Start')),
                ('end_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='End')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EducationGroupType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('category', models.CharField(choices=[('TRAINING', 'Training'), ('MINI_TRAINING', 'Mini-Training'), ('GROUP', 'Group')], default='TRAINING', max_length=25, verbose_name='Category')),
                ('name', models.CharField(max_length=255, verbose_name='Type of training')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EducationGroupYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('acronym', models.CharField(db_index=True, max_length=40, verbose_name='Acronym')),
                ('partial_acronym', models.CharField(db_index=True, max_length=15, null=True, verbose_name='Code')),
                ('title', models.CharField(max_length=255, verbose_name='Title in French')),
                ('dissertation', models.BooleanField(default=False, verbose_name='dissertation')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.AcademicYear', verbose_name='Validity')),
                ('administration_entity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='administration_entity', to='base.Entity', verbose_name='Administration entity')),
                ('education_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.EducationGroup')),
                ('education_group_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.EducationGroupType', verbose_name='Type of training')),
                ('management_entity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='management_entity', to='base.Entity', verbose_name='Management entity')),
            ],
            options={
                'verbose_name': 'Education group year',
            },
        ),
        migrations.AlterUniqueTogether(
            name='educationgroupyear',
            unique_together=set([('education_group', 'academic_year')]),
        ),
    ]
