# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-30 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0043_auto_20181119_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationgroup',
            name='external_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='educationgrouptype',
            name='external_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='educationgroupyear',
            name='external_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
