# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-07 13:26
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0045_auto_20181203_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerenrollment',
            name='education_group_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.EducationGroupYear'),
        ),
    ]
