# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-04-05 13:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0047_entityversion_entity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningcomponentyear',
            name='learning_unit_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.LearningUnitYear'),
        ),
        migrations.AlterField(
            model_name='learningcomponentyear',
            name='learning_container_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.LearningContainerYear'),
        ),
    ]
