# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-02-13 09:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0047_entityversion_entity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationgroupyear',
            name='education_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_groups_years', to='base.EducationGroup'),
        ),
        migrations.AlterField(
            model_name='offerenrollment',
            name='education_group_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offer_enrollments', to='base.EducationGroupYear'),
        ),
    ]
