# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-04-08 13:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0049_populate_learning_unit_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningunitcomponent',
            name='learning_component_year',
        ),
        migrations.RemoveField(
            model_name='learningunitcomponent',
            name='learning_unit_year',
        ),
        migrations.DeleteModel(
            name='LearningUnitComponent',
        ),
    ]
