# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-05-15 15:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0053_auto_20190515_1714'),
    ]

    operations = [
        migrations.RunSQL(
            """               
                update base_learningcomponentyear
                
                set 
                    repartition_volume_requirement_entity = ecy_requirement.repartition_volume
                from 
                    base_entitycomponentyear as ecy_requirement, base_entitycontaineryear as requirement_entity_container
                where (
                    ecy_requirement.learning_component_year_id = base_learningcomponentyear.id 
                    and ecy_requirement.entity_container_year_id = requirement_entity_container.id 
                    and requirement_entity_container.type = 'REQUIREMENT_ENTITY'
                )
            """
        ),

        migrations.RunSQL(
            """               
                update base_learningcomponentyear
                
                set 
                    repartition_volume_additional_entity_1 = ecy_additional_1.repartition_volume
                from 
                    base_entitycomponentyear as ecy_additional_1, base_entitycontaineryear as additional_entity_container_1
                where (
                    ecy_additional_1.learning_component_year_id = base_learningcomponentyear.id 
                    and ecy_additional_1.entity_container_year_id = additional_entity_container_1.id 
                    and additional_entity_container_1.type = 'ADDITIONAL_REQUIREMENT_ENTITY_1'
                )
            """
        ),

        migrations.RunSQL(
            """               
                update base_learningcomponentyear
                
                set 
                    repartition_volume_additional_entity_2 = ecy_additional_2.repartition_volume
                from 
                    base_entitycomponentyear as ecy_additional_2, base_entitycontaineryear as additional_entity_container_2
                where (
                    ecy_additional_2.learning_component_year_id = base_learningcomponentyear.id 
                    and ecy_additional_2.entity_container_year_id = additional_entity_container_2.id 
                    and additional_entity_container_2.type = 'ADDITIONAL_REQUIREMENT_ENTITY_2'
                )
            """
        ),

    ]
