# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-06-17 08:26
from __future__ import unicode_literals

import base.models.learning_container_year
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0055_auto_20190515_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningcontaineryear',
            name='additionnal_entity_1',
            field=base.models.learning_container_year.ForeignKeyEntityField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='additionnal_entities_1', to='base.Entity'),
        ),
        migrations.AddField(
            model_name='learningcontaineryear',
            name='additionnal_entity_2',
            field=base.models.learning_container_year.ForeignKeyEntityField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='additionnal_entities_2', to='base.Entity'),
        ),
        migrations.AddField(
            model_name='learningcontaineryear',
            name='allocation_entity',
            field=base.models.learning_container_year.ForeignKeyEntityField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allocation_entities', to='base.Entity'),
        ),
        migrations.AddField(
            model_name='learningcontaineryear',
            name='requirement_entity',
            field=base.models.learning_container_year.ForeignKeyEntityField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requirement_entities', to='base.Entity'),
        ),
    ]
