# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-07-23 09:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0058_auto_20190617_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academiccalendar',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.AcademicYear'),
        ),
        migrations.AlterField(
            model_name='campus',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.Organization'),
        ),
        migrations.AlterField(
            model_name='educationgroupyear',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.AcademicYear', verbose_name='Validity'),
        ),
        migrations.AlterField(
            model_name='educationgroupyear',
            name='administration_entity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='administration_entity', to='base.Entity', verbose_name='Administration entity'),
        ),
        migrations.AlterField(
            model_name='educationgroupyear',
            name='education_group_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.EducationGroupType', verbose_name='Type of training'),
        ),
        migrations.AlterField(
            model_name='educationgroupyear',
            name='management_entity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='management_entity', to='base.Entity', verbose_name='Management entity'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.Organization'),
        ),
        migrations.AlterField(
            model_name='entityversion',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.Entity'),
        ),
        migrations.AlterField(
            model_name='entityversion',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parent_of', to='base.Entity'),
        ),
        migrations.AlterField(
            model_name='learningcontaineryear',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.AcademicYear'),
        ),
        migrations.AlterField(
            model_name='learningcontaineryear',
            name='learning_container',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='base.LearningContainer'),
        ),
        migrations.AlterField(
            model_name='learningunitenrollment',
            name='learning_unit_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.LearningUnitYear'),
        ),
        migrations.AlterField(
            model_name='learningunityear',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.AcademicYear'),
        ),
        migrations.AlterField(
            model_name='learningunityear',
            name='learning_container_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.LearningContainerYear'),
        ),
        migrations.AlterField(
            model_name='learningunityear',
            name='learning_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.LearningUnit'),
        ),
        migrations.AlterField(
            model_name='offerenrollment',
            name='offer_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.OfferYear'),
        ),
        migrations.AlterField(
            model_name='offerenrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.Student'),
        ),
        migrations.AlterField(
            model_name='offeryear',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.AcademicYear'),
        ),
        migrations.AlterField(
            model_name='offeryear',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.Campus'),
        ),
        migrations.AlterField(
            model_name='offeryear',
            name='grade_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reference.GradeType'),
        ),
        migrations.AlterField(
            model_name='offeryear',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.Offer'),
        ),
        migrations.AlterField(
            model_name='offeryeardomain',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reference.Domain'),
        ),
        migrations.AlterField(
            model_name='student',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.Person'),
        ),
    ]
