# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-11-12 13:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0059_auto_20190723_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationgroup',
            name='end_year',
        ),
        migrations.RemoveField(
            model_name='educationgroup',
            name='start_year',
        ),
    ]
