# Generated by Django 2.2.5 on 2019-12-03 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0060_auto_20191112_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningunitenrollment',
            name='changed',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='learningunitenrollment',
            name='learning_unit_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.LearningUnitYear'),
        ),
        migrations.AlterField(
            model_name='learningunitenrollment',
            name='offer_enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.OfferEnrollment'),
        ),
    ]
