# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-01-14 09:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0060_auto_20191112_1420'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='learningunitenrollment',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='learningunitenrollment',
            name='learning_unit_year',
        ),
        migrations.RemoveField(
            model_name='learningunitenrollment',
            name='offer_enrollment',
        ),
        migrations.DeleteModel(
            name='LearningUnitEnrollment',
        ),
    ]
