# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-08-31 13:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0061_auto_20200123_1002'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSpecificProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('changed', models.DateTimeField(auto_now=True, null=True)),
                ('type', models.CharField(choices=[('Not defined', 'Not defined'), ('DDI', 'DDI'), ('Sport', 'Sport'), ('Artist', 'Artist'), ('Entrepreneur', 'Entrepreneur'), ('Educational facilities accepted by Jury', 'Educational facilities accepted by Jury')], max_length=20)),
                ('subtype_disability', models.CharField(blank=True, choices=[('Person with reduced mobility', 'Person with reduced mobility'), ('Other special needs', 'Other special needs')], max_length=20, verbose_name='Sub type Disability')),
                ('subtype_sport', models.CharField(blank=True, choices=[('High Level Promising athlete', 'High Level Promising athlete'), ('Promising athlete', 'Promising athlete')], max_length=20, verbose_name='Sub type Sport')),
                ('arrangement_additional_time', models.BooleanField(default=False, verbose_name='Arrangement additional time')),
                ('arrangement_appropriate_copy', models.BooleanField(default=False, verbose_name='Arrangement appropriate copy')),
                ('arrangement_other', models.BooleanField(default=False, verbose_name='Arrangement other')),
                ('arrangement_specific_locale', models.BooleanField(default=False, verbose_name='Arrangement specific locale')),
                ('guide', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.Person', verbose_name='Guide')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='base.Student')),
            ],
            options={
                'ordering': ('student', 'guide__last_name', 'guide__first_name'),
            },
        ),
    ]
