# Generated by Django 2.2.10 on 2020-09-03 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0061_auto_20200123_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningcontaineryear',
            name='container_type',
            field=models.CharField(choices=[('COURSE', 'Course'), ('INTERNSHIP', 'Internship'), ('DISSERTATION', 'Dissertation'), ('OTHER_COLLECTIVE', 'Other collective'), ('OTHER_INDIVIDUAL', 'Other individual'), ('MASTER_THESIS', 'Thesis'), ('EXTERNAL', 'External')], max_length=20, null=True),
        ),
    ]
