# Generated by Django 2.2.10 on 2020-09-03 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0061_auto_20200123_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningcontaineryear',
            name='container_type',
            field=models.CharField(choices=[('Course', 'Course'), ('Internship', 'Internship'), ('Dissertation', 'Dissertation'), ('Other collective', 'Other collective'), ('Other individual', 'Other individual'), ('Thesis', 'Thesis'), ('External', 'External')], max_length=20, null=True),
        ),
    ]
