# Generated by Django 2.2.13 on 2020-12-18 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0063_studentspecificprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningcontaineryear',
            name='in_charge',
        ),
    ]
