# Generated by Django 2.2.13 on 2021-01-21 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0064_auto_20201218_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentspecificprofile',
            name='subtype_disability',
            field=models.CharField(blank=True, choices=[('REDUCED_MOBILITY', 'Person with reduced mobility'), ('OTHER_DISABILITY', 'Other special needs')], max_length=20, verbose_name='Sub type Disability'),
        ),
        migrations.AlterField(
            model_name='studentspecificprofile',
            name='subtype_sport',
            field=models.CharField(blank=True, choices=[('PROMISING_ATHLETE_HL', 'High Level Promising athlete'), ('PROMISING_ATHLETE', 'Promising athlete')], max_length=20, verbose_name='Sub type Sport'),
        ),
        migrations.AlterField(
            model_name='studentspecificprofile',
            name='type',
            field=models.CharField(choices=[('NOT_DEFINED', 'Not defined'), ('DISABILITY', 'DDI'), ('SPORT', 'Sport'), ('ARTIST', 'Artist'), ('ENTREPRENEUR', 'Entrepreneur'), ('ARRANGEMENT_JURY', 'Educational facilities accepted by Jury')], max_length=20),
        ),
        migrations.DeleteModel(
            name='AcademicCalendar',
        ),
    ]
