# Generated by Django 2.2.10 on 2021-02-09 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0065_auto_20210121_1509'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'permissions': (('is_tutor', 'Is tutor'), ('is_student', 'Is student'), ('is_administrator', 'Is administrator'), ('is_internship_master', 'Is internship master'), ('is_faculty_administrator', 'Is faculty administrator'), ('can_access_administration', 'Can access administration'))},
        ),
    ]
