# Generated by Django 2.2.13 on 2021-03-12 16:04
from django.db import migrations


def populate_or_delete_offer_enrollment_education_group_year_id(apps, schema_editor):
    """Same script as migration file 0576 in Osis"""
    OfferEnrollment = apps.get_model('base', 'offerenrollment')
    EducationGroupYear = apps.get_model('base', 'educationgroupyear')
    off_enrollments_without_educ_group = OfferEnrollment.objects.filter(
        education_group_year_id__isnull=True
    ).select_related(
        'offer_year__academic_year'
    )
    deleted = set()
    for obj in off_enrollments_without_educ_group:
        education_group_year_id = EducationGroupYear.objects.filter(
            acronym=obj.offer_year.acronym,
            academic_year=obj.offer_year.academic_year,
        ).values_list('pk', flat=True).first()
        if not education_group_year_id:
            deleted.add('Removing all offerenrollments of {} in {}'.format(obj.offer_year.acronym, obj.offer_year.academic_year.year))
            obj.delete()
        else:
            obj.education_group_year_id = education_group_year_id
            obj.save()
    for msg in sorted(deleted):
        print(msg)


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0067_studentspecificprofile_comment'),
    ]

    operations = [
        migrations.RunPython(populate_or_delete_offer_enrollment_education_group_year_id),
    ]
