# Generated by Django 2.2.13 on 2021-03-15 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0069_auto_20210217_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentspecificprofile',
            name='arrangement_comment',
            field=models.CharField(blank=True, max_length=2000, null=True,
                                   verbose_name='Details other educational facilities'),
        ),
    ]
