# Generated by Django 2.2.13 on 2021-03-25 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0069_auto_20210217_1301'),
        ('base', '0068_auto_20210315_1432'),
    ]

    operations = [
    ]
