# Generated by Django 2.2.13 on 2021-03-25 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0070_merge_20210325_1102'),
        ('base', '0070_studentspecificprofile_translation'),
    ]

    operations = [
    ]
