# Generated by Django 2.2.13 on 2021-03-25 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0071_merge_20210325_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(default='', max_length=255),
        ),
    ]
