# Generated by Django 2.2.13 on 2021-06-15 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0071_merge_20210325_1133'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LearningComponentYear',
        ),
    ]
