# Generated by Django 2.2.13 on 2021-09-13 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0082_auto_20210909_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentspecificprofile',
            name='subtype_disability',
            field=models.CharField(blank=True, choices=[('REDUCED_MOBILITY', 'PMR'), ('OTHER_DISABILITY', 'Other special needs')], max_length=20, verbose_name='Sub type Disability'),
        ),
        migrations.AlterField(
            model_name='studentspecificprofile',
            name='subtype_sport',
            field=models.CharField(blank=True, choices=[('PROMISING_ATHLETE_HL', 'ESHN'), ('PROMISING_ATHLETE', 'ES')], max_length=20, verbose_name='Sub type Sport'),
        ),
    ]
