# Generated by Django 2.2.13 on 2021-09-30 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0082_auto_20210909_1715'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Campus',
        ),
    ]
