# Generated by Django 2.2.13 on 2021-09-30 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0082_auto_20210909_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(default='', max_length=255),
        ),
    ]
