# Generated by Django 2.2.13 on 2021-09-30 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0083_auto_20210930_1037'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='learningunitenrollment',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='learningunitenrollment',
            name='learning_unit_year',
        ),
        migrations.RemoveField(
            model_name='learningunitenrollment',
            name='offer_enrollment',
        ),
        migrations.RemoveField(
            model_name='studentspecificprofile',
            name='guide',
        ),
        migrations.RemoveField(
            model_name='studentspecificprofile',
            name='student',
        ),
        migrations.DeleteModel(
            name='Campus',
        ),
        migrations.DeleteModel(
            name='LearningUnitEnrollment',
        ),
        migrations.DeleteModel(
            name='StudentSpecificProfile',
        ),
    ]
