# Generated by Django 2.2.13 on 2021-09-30 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0083_delete_campus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LearningUnitEnrollment',
        ),
    ]
