# Generated by Django 2.2.13 on 2021-09-30 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0084_delete_learningunitenrollment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentSpecificProfile',
        ),
    ]
