# Generated by Django 2.2.13 on 2021-10-25 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0084_auto_20210930_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='organization',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
