# Generated by Django 2.2.13 on 2021-09-30 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0085_delete_studentspecificprofile'),
        ('base', '0083_auto_20210930_1037'),
        ('base', '0083_auto_20210913_1509'),
    ]

    operations = [
    ]
