# Generated by Django 2.2.13 on 2021-10-25 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0085_auto_20211025_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningcontaineryear',
            name='learning_container',
        ),
        migrations.DeleteModel(
            name='LearningContainer',
        ),
    ]
