# Generated by Django 2.2.13 on 2021-11-09 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0085_auto_20211025_0947'),
        ('base', '0085_auto_20211025_1104'),
    ]

    operations = [
    ]
