# Generated by Django 2.2.13 on 2021-10-25 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0086_auto_20211025_1118'),
        ('base', '0085_auto_20211025_0947'),
    ]

    operations = [
    ]
