# Generated by Django 2.2.13 on 2021-11-09 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0086_merge_20211109_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningcontaineryear',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='learningcontaineryear',
            name='additional_entity_1',
        ),
        migrations.RemoveField(
            model_name='learningcontaineryear',
            name='additional_entity_2',
        ),
        migrations.RemoveField(
            model_name='learningcontaineryear',
            name='allocation_entity',
        ),
        migrations.RemoveField(
            model_name='learningcontaineryear',
            name='requirement_entity',
        ),
        migrations.DeleteModel(
            name='LearningUnit',
        ),
        migrations.AlterUniqueTogether(
            name='learningunityear',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='learningunityear',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='learningunityear',
            name='learning_container_year',
        ),
        migrations.DeleteModel(
            name='LearningContainerYear',
        ),
        migrations.DeleteModel(
            name='LearningUnitYear',
        ),
    ]
