# Generated by Django 3.2.18 on 2023-03-15 13:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0087_auto_20211109_1711'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LearningContainer',
        ),
    ]
