# Generated by Django 2.2.13 on 2021-11-08 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0087_merge_20211025_1431'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LearningContainerYear',
        ),
        migrations.DeleteModel(
            name='LearningUnitYear',
        ),
        migrations.DeleteModel(
            name='LearningUnit',
        ),
    ]
