# Generated by Django 2.2.13 on 2021-11-08 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0087_merge_20211025_1431'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='learningunityear',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='learningunityear',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='learningunityear',
            name='learning_container_year',
        ),
        migrations.RemoveField(
            model_name='learningunityear',
            name='learning_unit',
        ),
        migrations.DeleteModel(
            name='LearningContainerYear',
        ),
        migrations.DeleteModel(
            name='LearningUnit',
        ),
        migrations.DeleteModel(
            name='LearningUnitYear',
        ),
    ]
