# Generated by Django 3.2.20 on 2023-09-04 08:56

from django.db import migrations


def replace_global_id_empty_str_to_null(apps, schema_editor):
    Person = apps.get_model('base', 'Person')
    qs = Person.objects.filter(global_id='')
    for person in qs:
        person.global_id = None
        person.save()


def replace_global_id_null_to_empty_str(apps, schema_editor):
    Person = apps.get_model('base', 'Person')
    qs = Person.objects.filter(global_id__isnull=True)
    for person in qs:
        person.global_id = ''
        person.save()


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0089_alter_person_global_id'),
    ]

    operations = [
        migrations.RunPython(replace_global_id_empty_str_to_null, replace_global_id_null_to_empty_str),
    ]
