# Generated by Django 3.2.20 on 2023-09-06 14:40

from django.db import migrations


def set_username_as_global_id(apps, schema_editor):
    Person = apps.get_model('base', 'Person')

    persons_qs = Person.objects.filter(
        global_id__isnull=False,
        # Continuing education use django authentification, we cannot change username of all of records.
        # If password set, we can conclude that it is user which come from Continuing education registration
        user__password=''
    ).select_related('user')

    for person in persons_qs:
        person.user.username = person.global_id
        person.user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0091_alter_person_global_id'),
    ]

    operations = [
        migrations.RunPython(set_username_as_global_id, reverse_code=migrations.RunPython.noop, elidable=True)
    ]
