# Generated by Django 3.2.20 on 2023-10-30 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0093_alter_person_gender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'permissions': (('is_tutor', 'Is tutor'), ('is_student', 'Is student'), ('is_administrator', 'Is administrator'), ('is_internship_master', 'Is internship master'), ('is_faculty_administrator', 'Is faculty administrator'), ('can_access_administration', 'Can access administration'), ('can_access_internship', 'Can access internship'))},
        ),
    ]
