# Generated by Django 3.2.24 on 2024-02-23 08:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0095_person_birth_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OfferEnrollment',
        ),
    ]
